COMPILE_DEPS = [
    '//lib:CORE_DEPS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Mastership Load Balancer App',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'Application that balances mastership among nodes.',
)
