COMPILE_DEPS = [
    '//lib:CORE_DEPS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Mastership Load Balancer',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'Monitors distribution of mastership of network devices between the ONOS cluster ' +
        'nodes and periodically re-assigns the mastership to achieve balanced distribution when ' +
        'necessary and possible.',
)
