osgi_jar_with_tests(
    deps = CORE_DEPS,
)

onos_app(
    category = "Utility",
    description = "Monitors distribution of mastership of network devices between the ONOS cluster " +
                  "nodes and periodically re-assigns the mastership to achieve balanced distribution when " +
                  "necessary and possible.",
    title = "Mastership Load Balancer",
    url = "http://onosproject.org",
)
