COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//lib:io_netty_netty_transport',
    '//lib:io_netty_netty_buffer',
    '//lib:io_netty_netty_codec',
    '//protocols/tl1/api:onos-protocols-tl1-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//utils/osgi:onlab-osgi-tests',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
