BUNDLES = [
    '//apps/routing/common:onos-apps-routing-common',
    '//apps/routing-api:onos-apps-routing-api',
    '//apps/routing/fpm/api:onos-apps-routing-fpm-api',
    '//apps/routing/fpm/app:onos-apps-routing-fpm-app',
]

onos_app (
    app_name = 'org.onosproject.fpm',
    title = 'FIB Push Manager (FPM) Route Receiver',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'Receives/Transmits routes from external routing daemon over FPM protocol',
    included_bundles = BUNDLES,
    required_apps = [ 'org.onosproject.route-service' ],
)