COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/ovsdb/api:onos-protocols-ovsdb-api',
    '//protocols/ovsdb/rfc:onos-protocols-ovsdb-rfc',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//protocols/ovsdb/api:onos-protocols-ovsdb-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.ovsdb',
    title = 'OVSDB Device Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS OVSDB Device Drivers application.',
    required_apps = [ 'org.onosproject.ovsdb-base' ],
)
