COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/ovsdb/api:onos-ovsdb-api',
    '//protocols/ovsdb/rfc:onos-ovsdb-rfc',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//protocols/ovsdb/api:onos-protocols-ovsdb-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    title = 'OVSDB Device Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS OVSDB Device Drivers application.',
)
