BUNDLES = [
    "//apps/mappingmanagement/api:onos-apps-mappingmanagement-api",
    "//apps/mappingmanagement/cli:onos-apps-mappingmanagement-cli",
    "//apps/mappingmanagement/mgr:onos-apps-mappingmanagement-mgr",
    "//apps/mappingmanagement/web:onos-apps-mappingmanagement-web",
]

onos_app(
    category = "Monitoring",
    description = "ONOS mapping management application",
    included_bundles = BUNDLES,
    title = "Mapping Management",
    url = "https://onosproject.org/",
)
