include_defs('//bucklets/grpc.bucklet')

PROTOBUF_VER = '3.2.0'
GRPC_VER = '1.3.1'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//lib:grpc-stub-' + GRPC_VER,
    '//lib:grpc-protobuf-' + GRPC_VER,
    '//lib:protobuf-java-' + PROTOBUF_VER,
]

grpc_jar(
    deps = COMPILE_DEPS,
    # FIXME should not be manually building absolute path.
    # Come up with glob(..) equivalent in BUCK which can handle directory.
    proto_paths = ["$ONOS_ROOT/protocols/gnmi/stub/src/main/proto"],
    include_std_lib = True,
)

project_config(
    src_target = ':onos-protocols-gnmi-stub'
)
