COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//cli:onos-cli',
    '//lib:httpclient-osgi',
    '//lib:httpcore-osgi',
    '//lib:org.apache.httpcomponents.httpasyncclient-osgi',
    '//lib:org.apache.httpcomponents.httpcore-nio',
    '//lib:org.apache.karaf.shell.console',
    '//lib:org.apache.karaf.jaas',

]
TEST_DEPS = [
  '//lib:TEST',
]

BUNDLES = [
  ':onos-apps-gluon',
  '//lib:httpclient-osgi',
  '//lib:httpcore-osgi',
  '//lib:org.apache.httpcomponents.httpasyncclient-osgi',
  '//lib:org.apache.httpcomponents.httpcore-nio',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
    app_name = 'org.onosproject.gluon',
    title = 'Gluon Shim',
    category = 'Monitoring',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
    description = 'To fetch data from Gluon Server over Http session.',
)
