BUNDLES = [
    '//protocols/isis/api:onos-protocols-isis-api',
    '//protocols/isis/ctl:onos-protocols-isis-ctl',
    '//protocols/isis/isisio:onos-protocols-isis-isisio',
    '//providers/isis/cfg:onos-providers-isis-cfg',
    '//providers/isis/topology:onos-providers-isis-topology',
]

onos_app (
    title = 'ISIS Provider',
    category = 'Provider',
    url = 'http://onosproject.org',
    description = 'ONOS ISIS protocol adapters.',
    included_bundles = BUNDLES,
)

