#!/bin/bash

ONOS_INSTALL_LOCATION=$2
echo ${ONOS_INSTALL_LOCATION}

export NODEJS_HOME=${ONOS_INSTALL_LOCATION}/
export PATH=$NODEJS_HOME/bin:$PATH

cd $ONOS_ROOT/tools/gui
# Install NPM Global packages
ONOS_NPM_GLOBAL_DEPENDENCIES="gulp-cli gulp"
echo "Installing NPM Global dependencies: $ONOS_NPM_GLOBAL_DEPENDENCIES"
npm install -g ${ONOS_NPM_GLOBAL_DEPENDENCIES} --loglevel=error

# Install Project Dependencies
echo "Installing project dependencies"
npm install --loglevel=error

# Build the GUI Project
echo "Packaging JavaScript and CSS"
npm run build