COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//lib:openflowj',
    '//protocols/openflow/api:onos-protocols-openflow-api',
    '//providers/openflow/flow:onos-providers-openflow-flow',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
