COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:openflowj',
    '//protocols/openflow/api:onos-of-api',
    '//providers/openflow/flow:onos-providers-openflow-flow',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
