COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//incubator/api:onos-incubator-api',
#   '//core/store/serializers:onos-core-serializers',
  '//apps/network-troubleshoot/api:onos-apps-network-troubleshoot-api',
]

TEST_DEPS = [
  '//lib:TEST_ADAPTERS',
  '//utils/osgi:onlab-osgi-tests',
  '//incubator/api:onos-incubator-api-tests',
]

osgi_jar_with_tests (
  deps = COMPILE_DEPS,
  test_deps = TEST_DEPS,
)
