GRPC_VER = '1.3.0'
PROTOBUF_VER = '3.0.2'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/grpc/api:onos-protocols-grpc-api',
    '//protocols/grpc/ctl:onos-protocols-grpc-ctl',
    '//protocols/p4runtime/api:onos-protocols-p4runtime-api',
    '//protocols/p4runtime/ctl:onos-protocols-p4runtime-ctl',
    '//protocols/p4runtime/proto:onos-protocols-p4runtime-proto',
    '//drivers/bmv2:onos-drivers-bmv2',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//lib:grpc-stub-' + GRPC_VER,
    '//lib:protobuf-java-' + PROTOBUF_VER,
]

TEST_DEPS = [
    '//lib:TEST',
    '//lib:slf4j-jdk14',
    '//incubator/bmv2/model:onos-incubator-bmv2-model',
    # gRPC dependencies
    '//lib:grpc-protobuf-' + GRPC_VER,
    '//lib:grpc-protobuf-lite-' + GRPC_VER,
    '//lib:grpc-netty-' + GRPC_VER,
    '//lib:grpc-auth-' + GRPC_VER,
    '//lib:google-instrumentation-0.3.0',
    # Lazily adding all netty-related packages.
    # Some of them might not be necessary.
    '//lib:netty',
    '//lib:netty-buffer',
    '//lib:netty-codec',
    '//lib:netty-codec-http',
    '//lib:netty-codec-http2',
    '//lib:netty-common',
    '//lib:netty-handler',
    '//lib:netty-transport',
    '//lib:netty-transport-native-epoll',
    '//lib:netty-resolver',
    '//lib:minimal-json',
]

java_test(
    name = "onos-apps-p4runtime-test-tests",
    srcs = glob([ 'src/test/java/**/*.java' ]),
    deps = COMPILE_DEPS + TEST_DEPS,
)
