
filegroup(
    name = "onos-admin",
    srcs = [
        "bin/onos",
      ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "onos-test",
    srcs = glob(["**/*"]),
    visibility = ["//visibility:public"],
)