COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//core/store/serializers:onos-core-serializers',
    '//apps/openstackinterface/api:onos-apps-openstackinterface-api',
    '//apps/openstacknetworking/api:onos-apps-openstacknetworking-api',
    '//apps/openstacknode:onos-apps-openstacknode',
    '//apps/dhcp/api:onos-apps-dhcp-api',
]

BUNDLES = [
    '//apps/openstacknetworking/api:onos-apps-openstacknetworking-api',
    '//apps/openstacknetworking/web:onos-apps-openstacknetworking-web',
    '//apps/openstacknetworking/switching:onos-apps-openstacknetworking-switching',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.openstackswitching',
    title = 'OpenStack Switching App',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'OpenStack Switching application.',
    included_bundles = BUNDLES,
    required_apps = [ 'org.onosproject.openstackinterface', 'org.onosproject.openstacknode', 'org.onosproject.dhcp' ]
)
