COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:ONOS_YANG',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//protocols/netconf/ctl:onos-protocols-netconf-ctl',
    '//models/common:onos-models-common',
    '//models/microsemi:onos-models-microsemi',
    '//lib:org.apache.karaf.shell.console',
    '//apps/cfm/api:onos-apps-cfm-api',
] + YANG_TOOLS

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//drivers/netconf:onos-drivers-netconf-tests',
    '//utils/osgi:onlab-osgi-tests',
    '//apps/cfm/app:onos-apps-cfm-app',
    '//apps/cfm/app:onos-apps-cfm-app-tests',
]

APPS = [
    'org.onosproject.yang',
#     'org.onosproject.yang-gui',
    'org.onosproject.config',
    'org.onosproject.netconf',
    'org.onosproject.netconfsb',
    'org.onosproject.drivers.netconf',
    'org.onosproject.models.common',
    'org.onosproject.models.microsemi',
    'org.onosproject.cfm',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.microsemi.ea1000',
    title = 'Microsemi Drivers EA1000',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'Adds support for Microsemi EA1000 devices.',
    required_apps = APPS,
)
