#!/bin/bash
# -----------------------------------------------------------------------------
# Starts ATT ONOS topology in mininet.
# -----------------------------------------------------------------------------
cd $(dirname $0)
if [ -n "$1" ]; then
    sudo python att-onos.py "$@"
else
    sudo python att-onos.py 10.128.11.1 10.128.11.2 10.128.11.3
fi
