#!/bin/bash
# -----------------------------------------------------------------------------
# Starts the specified mininet topology.
# -----------------------------------------------------------------------------
cd $(dirname $0)

topo=${1:-att-onos.py}

[ -n "$1" ] && shift
sudo python $topo "$@"
