COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/netconf/api:onos-protocols-netconf-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//lib:slf4j-jdk14',
    '//core/api:onos-api-tests',
]

BUNDLES = [
    ':onos-drivers-netconf',
    '//drivers/utilities:onos-drivers-utilities',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.netconf',
    title = 'Generic NETCONF Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'Adds support for devices using NETCONF.',
    included_bundles = BUNDLES,
    required_apps = [ 'org.onosproject.netconf' ],
)
