BUNDLES = [
    '//apps/vtn/vtnrsc:onos-apps-vtn-vtnrsc',
    '//apps/vtn/sfcmgr:onos-apps-vtn-sfcmgr',
    '//apps/vtn/vtnmgr:onos-apps-vtn-vtnmgr',
    '//apps/vtn/vtnweb:onos-apps-vtn-vtnweb',
]

onos_app (
  title = 'OPNFV',
  url = 'http://onosproject.org',
  category = 'Integration',
  included_bundles = BUNDLES,
  description = 'ONOS framework applications',
)
