COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.karaf.shell.console',
    '//incubator/api:onos-incubator-api',
    '//cli:onos-cli',
    '//utils/osgi:onlab-osgi',
    '//core/store/serializers:onos-core-serializers',
    '//apps/openstacknetworking/api:onos-apps-openstacknetworking-api',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
