include_defs('//apps/openstacknode/openstack4j.bucklet')

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:openstack4j-core',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,

    import_packages = INCLUDE_PACKAGES + ',' + EXCLUDE_PACKAGES  + ',' + ALL_PACKAGES,
)
