APPS = [
    'org.onosproject.hostprovider',
    'org.onosproject.lldpprovider',
    'org.onosproject.openflow-base',
]

onos_app (
    app_name = 'org.onosproject.openflow',
    title = 'OpenFlow Meta App',
    category = 'Provider',
    url = 'http://onosproject.org',
    description = 'OpenFlow southbound meta application.',
    included_bundles = [ '//utils/osgi:onlab-osgi' ],  # FIXME to allow hollow oar files
    required_apps = APPS,
)
