COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/api:onos-incubator-api',
    '//protocols/ovsdb/api:onos-protocols-ovsdb-api',
    '//protocols/ovsdb/rfc:onos-protocols-ovsdb-rfc',
    '//apps/pcep-api:onos-apps-pcep-api',
    '//protocols/pcep/api:onos-protocols-pcep-api',
    '//protocols/pcep/pcepio:onos-protocols-pcep-pcepio',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
