COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
    '//utils/rest:onlab-rest',
    '//lib:javax.ws.rs-api',
    '//core/store/serializers:onos-core-serializers',
]

osgi_jar (
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.distributedprimitives',
    title = 'Distributed Primitives Test App',
    category = 'Test',
    url = 'http://onosproject.org',
    description = 'ONOS app to test distributed primitives.',
)
