COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:jersey-client',
    '//lib:javax.ws.rs-api',
    '//lib:jersey-server',
]

TEST_DEPS = [
    '//lib:TEST_REST',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
