BUNDLES = [
    '//protocols/pcep/server/api:onos-protocols-pcep-server-api',
    '//protocols/pcep/server/ctl:onos-protocols-pcep-server-ctl',
]

onos_app (
  title = 'PCEP Server Module',
  category = 'Utility',
  url = 'http://onosproject.org',
  included_bundles = BUNDLES,
)
