BUNDLES = [
    "//protocols/pcep/server/api:onos-protocols-pcep-server-api",
    "//protocols/pcep/server/ctl:onos-protocols-pcep-server-ctl",
]

onos_app(
    category = "Utility",
    included_bundles = BUNDLES,
    title = "PCEP Server Module",
    url = "http://onosproject.org",
)
