COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//lib:JACKSON',
    '//protocols/ospf/api:onos-protocols-ospf-api',
    '//protocols/ospf/protocol:onos-protocols-ospf-protocol',
    '//lib:netty',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

