COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/ospf/api:onos-protocols-ospf-api',
    '//protocols/ospf/protocol:onos-protocols-ospf-protocol',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

