BUNDLES = [
    "//apps/packet-stats/web:onos-apps-packet-stats-web",
    "//apps/packet-stats/app:onos-apps-packet-stats-app",
]

onos_app(
    app_name = "org.onosproject.packet-stats",
    category = "Utility",
    description = " Application to calculate the number of packets of different types",
    included_bundles = BUNDLES,
    title = "Packet Statistics",
    url = "http://onosproject.org",
)
