COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/grpc/api:onos-protocols-grpc-api',
    '//protocols/grpc/proto:onos-protocols-grpc-proto',
    '//lib:grpc-core-1.3.0',
    '//lib:grpc-protobuf-1.3.0',
    '//lib:grpc-stub-1.3.0',
    '//lib:grpc-netty-1.3.0',
    '//lib:grpc-auth-1.3.0',
    '//lib:protobuf-java-3.0.2',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//utils/osgi:onlab-osgi-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

