PROTOC_VER = '3.0.2'
GRPC_VER = '1.3.0'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/grpc/api:onos-protocols-grpc-api',
    '//protocols/grpc/proto:onos-protocols-grpc-proto',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//lib:grpc-stub-' + GRPC_VER,
    '//lib:protobuf-java-' + PROTOC_VER,
]

osgi_jar (
    deps = COMPILE_DEPS,
)

