osgi_jar (
    deps = CORE_DEPS + [
        "//protocols/grpc/api:onos-protocols-grpc-api",
        "//protocols/grpc/proto:dummy_java_grpc",
        "//protocols/grpc/proto:dummy_java_proto",
        "@io_grpc_grpc_java//core"
    ],
)
