BUNDLES = [
    '//providers/bgp/cfg:onos-providers-bgp-cfg',
    '//providers/bgp/topology:onos-providers-bgp-topology',
    '//providers/bgp/cli:onos-providers-bgp-cli',
    '//protocols/bgp/api:onos-protocols-bgp-api',
    '//protocols/bgp/ctl:onos-protocols-bgp-ctl',
    '//protocols/bgp/bgpio:onos-protocols-bgp-bgpio',
]

onos_app (
    title = 'BGP Provider',
    category = 'Provider',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
    description = 'BGP protocol southbound providers.',
)

