BUNDLES = [
    '//apps/openstacknetworking/api:onos-apps-openstacknetworking-api',
    '//apps/openstacknetworking/app:onos-apps-openstacknetworking-app',
]

onos_app (
    title = 'OpenStack Networking Application',
    category = 'Integration',
    url = 'https://wiki.onosproject.org/display/ONOS/SONA%3A+DC+Network+Virtualization',
    included_bundles = BUNDLES,
    description = 'SONA Openstack Networking Application.',
    required_apps = [
        'org.onosproject.openstacknode'
    ]
)
