BUNDLES = [
    '//apps/mcast/cli:onos-apps-mcast-cli',
    '//apps/mcast/impl:onos-apps-mcast-impl',
    '//apps/mcast/web:onos-apps-mcast-web',
    '//apps/mcast/api:onos-apps-mcast-api',
]

onos_app(
    title = 'Multicast traffic control',
    origin = 'ONF',
    description = 'Provides handling of multicast traffic.',
    category = 'Traffic Engineering',
    url = 'https://wiki.onosproject.org/',
    included_bundles = BUNDLES,
)
