BUNDLES = [
    "//apps/mcast/cli:onos-apps-mcast-cli",
    "//apps/mcast/impl:onos-apps-mcast-impl",
    "//apps/mcast/web:onos-apps-mcast-web",
    "//apps/mcast/api:onos-apps-mcast-api",
]

onos_app(
    category = "Traffic Engineering",
    description = "Provides handling of multicast traffic.",
    included_bundles = BUNDLES,
    origin = "ONOS Community",
    title = "Multicast traffic control",
    url = "https://wiki.onosproject.org/",
)
