COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:javax.ws.rs-api',
    '//incubator/api:onos-incubator-api',
    '//utils/rest:onlab-rest',
    '//drivers/utilities:onos-drivers-utilities',
    '//drivers/netconf:onos-drivers-netconf',
    '//protocols/netconf/api:onos-protocols-netconf-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//drivers/netconf:onos-drivers-netconf-tests',
    '//lib:slf4j-jdk14',
]

BUNDLES = [
    ':onos-drivers-ciena-c5162',
    '//drivers/utilities:onos-drivers-utilities',
    '//drivers/netconf:onos-drivers-netconf',
]

REQUIRED_APPS = [
    'org.onosproject.linkdiscovery',
    'org.onosproject.netconf',
    'org.onosproject.netconfsb',
    'org.onosproject.drivers.netconf'
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/*/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.ciena.c5162',
    title = 'Ciena 5162 Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'Adds support for Ciena 5162 devices.',
    included_bundles = BUNDLES,
    required_apps = REQUIRED_APPS,
)
