COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//lib:JACKSON',
    '//lib:KRYO',
    '//core/store/serializers:onos-core-serializers',
    '//core/common:onos-core-common',
    '//incubator/api:onos-incubator-api',
    '//cli:onos-cli',
    '//lib:org.apache.karaf.shell.console',
    '//lib:netty-transport',
    '//lib:netty-buffer',
    '//lib:netty-codec',
    '//lib:netty-handler',
    '//lib:openflowj',
    '//lib:javax.ws.rs-api',
    '//utils/rest:onlab-rest',
    '//providers/openflow/flow:onos-providers-openflow-flow',
    '//protocols/openflow/api:onos-protocols-openflow-api',
]

BUNDLES = [
    '//apps/ofagent:onos-apps-ofagent',
    '//providers/openflow/flow:onos-providers-openflow-flow',
    '//protocols/openflow/api:onos-protocols-openflow-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//core/common:onos-core-common-tests',
    '//lib:TEST_REST',
    '//lib:jersey-server',
    '//web/api:onos-rest-tests',
    '//lib:minimal-json',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    web_context = '/onos/ofagent',
    api_title = 'OFAgent API',
    api_version = '1.0',
    api_description = 'REST API for OFAgent',
    api_package = 'org.onosproject.ofagent.rest',
)

onos_app (
    title = 'OpenFlow Agent',
    category = 'Traffic Engineering',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
    description = 'OpenFlow agent application for virtualization subsystem.',
)
