CORE = [
    '//utils/osgi:onlab-osgi',
    '//utils/junit:onlab-junit',
    '//utils/misc:onlab-misc',
    '//utils/rest:onlab-rest',

    '//core/api:onos-api',
    '//core/net:onos-core-net',
    '//core/common:onos-core-common',
    '//core/store/primitives:onos-core-primitives',
    '//core/store/serializers:onos-core-serializers',
    '//core/store/dist:onos-core-dist',
    '//core/security:onos-security',
    '//core/store/persistence:onos-core-persistence',

    '//incubator/api:onos-incubator-api',
    '//incubator/net:onos-incubator-net',
    '//incubator/core:onos-incubator-core',
    '//incubator/store:onos-incubator-store',
    '//incubator/rpc:onos-incubator-rpc',

    '//cli:onos-cli',

    '//protocols/rest/api:onos-restsb-api',
    '//protocols/rest/ctl:onos-restsb-ctl',
    '//protocols/bgp/bgpio:onos-bgpio',
    '//protocols/bgp/api:onos-bgp-api',
    '//protocols/bgp/ctl:onos-bgp-ctl',
    '//protocols/netconf/api:onos-netconf-api',
    '//protocols/netconf/ctl:onos-netconf-ctl',
    '//protocols/openflow/api:onos-of-api',
    '//protocols/openflow/ctl:onos-of-ctl',
    '//protocols/ospf/api:onos-ospf-api',
    '//protocols/ospf/protocol:onos-ospf-protocol',
    '//protocols/ospf/ctl:onos-ospf-ctl',
    '//protocols/ovsdb/rfc:onos-ovsdb-rfc',
    '//protocols/ovsdb/api:onos-ovsdb-api',
    '//protocols/ovsdb/ctl:onos-ovsdb-ctl',
    '//protocols/pcep/pcepio:onos-pcep-pcepio',
    '//protocols/pcep/api:onos-pcep-controller-api',
    '//protocols/pcep/ctl:onos-pcep-ctl',
    '//protocols/snmp/api:onos-snmp-api',
    '//protocols/snmp/ctl:onos-snmp-ctl',
    '//protocols/isis:onos-isis-api',
    '//protocols/isis:onos-isis-isisio',

    '//drivers/utilities:onos-drivers-utilities',
    '//drivers/bti:onos-drivers-bti',
    '//drivers/ciena:onos-drivers-ciena',
    '//drivers/cisco:onos-drivers-cisco',
    '//drivers/default:onos-drivers-default',
    '//drivers/fujitsu:onos-drivers-fujitsu',
    '//drivers/lumentum:onos-drivers-lumentum',
    '//drivers/netconf:onos-drivers-netconf',
    '//drivers/ovsdb:onos-drivers-ovsdb',

    '//providers/bgp/cfg:onos-bgp-provider-cfg',
    '//providers/bgp/flow:onos-bgp-provider-flow',
    '//providers/bgp/topology:onos-bgp-provider-topology',
    '//providers/host:onos-host-provider',
    '//providers/lldpcommon:onos-lldp-provider-common',
    '//providers/netcfglinks:onos-netcfg-links-provider',
    '//providers/lldp:onos-lldp-provider',
    '//providers/netconf/device:onos-netconf-provider-device',
    '//providers/netcfghost:onos-netcfg-links-provider',
    '//providers/null:onos-null-providers',
    '//providers/openflow/device:onos-of-provider-device',
    '//providers/openflow/flow:onos-of-provider-flow',
    '//providers/openflow/group:onos-of-provider-group',
    '//providers/openflow/message:onos-of-provider-message',
    '//providers/openflow/meter:onos-of-provider-meter',
    '//providers/openflow/packet:onos-of-provider-packet',
    '//providers/ovsdb/device:onos-ovsdb-provider-device',
    '//providers/ovsdb/host:onos-ovsdb-provider-host',
    '//providers/ovsdb/tunnel:onos-ovsdb-provider-tunnel',
    '//providers/pcep/topology:onos-pcep-provider-topology',
    '//providers/pcep/tunnel:onos-pcep-provider-tunnel',
    '//providers/rest/device:onos-restsb-provider-device',
    '//providers/snmp/alarm:onos-snmp-provider-alarm',
    '//providers/snmp/device:onos-snmp-provider-device',

    '//web/api:onos-rest',
    '//web/gui:onos-gui',
]

APPS = [
    '//apps/dhcp:onos-apps-dhcp-oar',
    '//apps/fwd:onos-apps-fwd-oar',
]

APP_JARS = [
    '//apps/cpman/api:onos-app-cpman-api',
    '//apps/cpman/app:onos-app-cpman-app',
    '//apps/aaa:onos-app-aaa',
    '//apps/acl:onos-app-acl',
    '//apps/bgprouter:onos-app-bgprouter',
    '//apps/routing-api:onos-app-routing-api',
    '//apps/cip:onos-app-cip',
    '//apps/cordmcast:onos-app-cord-mcast',
    '//apps/cordvtn:onos-apps-cordvtn',
    '//apps/dhcp/api:onos-apps-dhcp-api',
    '//apps/dhcp/app:onos-apps-dhcp-app',
    '//apps/drivermatrix:onos-app-drivermatrix',
    '//apps/events:onos-app-events',
    '//apps/faultmanagement:onos-app-fm',
    '//apps/flowanalyzer:onos-app-flowanalyzer',
    '//apps/fwd:onos-apps-fwd',
    '//apps/igmp:onos-app-igmp',
    '//apps/influxdbmetrics:onos-app-influxdb',
    '//apps/olt:onos-app-olt-api',
    '//apps/olt:onos-app-olt-app',
    '//apps/iptopology-api:onos-app-iptopology-api',
    '//apps/metrics:onos-app-metrics',
    '//apps/gangliametrics:onos-app-ganglia',
    '//apps/graphitemetrics:onos-app-graphite',
    '//apps/mfwd:onos-app-mfwd',
    '//apps/mlb:onos-app-mlb',
    '//apps/mobility:onos-app-mobility',
    '//apps/openstackinterface:onos-app-openstackinterface-api',
    '//apps/openstackinterface:onos-app-openstackinterface-app',
    '//apps/openstacknetworking:onos-app-openstacknetworking',
    '//apps/openstacknode:onos-app-openstacknode',
    '//apps/optical:onos-app-optical',
    '//apps/pathpainter:onos-app-pp',
    '//apps/pim:onos-app-pim',
    '//apps/proxyarp:onos-app-proxyarp',
    '//apps/routing:onos-app-routing',
    '//apps/sdnip:onos-app-sdnip',
    '//apps/segmentrouting:onos-app-segmentrouting',
    '//apps/test:onos-app-test',
    '//apps/vtn:onos-app-vtn',
    '//apps/virtualbng:onos-app-virtualbng',
    '//apps/vpls:onos-app-vpls',
    '//apps/vrouter:onos-app-vrouter',
]

java_library(
    name = 'core',
    visibility = ['PUBLIC'],
    deps = CORE,
)

java_library(
    name = 'apps',
    visibility = ['PUBLIC'],
    deps = APPS + APP_JARS,
)

java_library(
    name = 'onos',
    visibility = ['PUBLIC'],
    deps = [ ':core', ':apps' ]
)

INSTALL = [
    '//utils/misc:onlab-misc-install',
    '//utils/osgi:onlab-osgi-install',
    '//utils/rest:onlab-rest-install',

    '//core/api:onos-api-install',
    '//incubator/api:onos-incubator-api-install',

    '//core/net:onos-core-net-install',
    '//core/common:onos-core-common-install',
    '//core/store/dist:onos-core-dist-install',
    '//core/store/primitives:onos-core-primitives-install',
    '//core/store/persistence:onos-core-persistence-install',
    '//core/store/serializers:onos-core-serializers-install',

    '//incubator/net:onos-incubator-net-install',
    '//incubator/core:onos-incubator-core-install',
    '//incubator/store:onos-incubator-store-install',
    '//incubator/rpc:onos-incubator-rpc-install',

    '//core/security:onos-security-install',

    '//web/api:onos-rest-install',
    '//web/gui:onos-gui-install',
    '//cli:onos-cli-install',
]
java_library(
    name = 'install',
    visibility = ['PUBLIC'],
    deps = INSTALL
)
