filegroup(
    name = "onos",
    srcs = [
        "//utils/junit:onlab-junit-osgi",
        "//utils/misc:onlab-misc-osgi",
        "//utils/osgi:onlab-osgi-osgi",
        "//utils/rest:onlab-rest-osgi",
        "//utils/osgiwrap:osgi-jar",
        "//core/api:onos-api-osgi",
        "//core/common:onos-core-common-osgi",
        "//incubator/api:onos-incubator-api-osgi",
        "//core/store/serializers:onos-core-serializers-osgi",
        "//core/store/dist:onos-core-dist-osgi",
        "//incubator/store:onos-incubator-store",
        "//incubator/net:onos-incubator-net",
        "//protocols/openflow/api:onos-protocols-openflow-api-osgi",
        "//drivers/default:onos-drivers-default-osgi",
        "//protocols/p4runtime/api:onos-protocols-p4runtime-api-osgi",
        "//protocols/p4runtime/model:onos-protocols-p4runtime-model-osgi",
        #"//core/net:onos-core-net-osgi",
    ],
)
