COMPILE_DEPS = [
    '//lib:CORE_DEPS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Packet/Optical Use-Case App',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'Packet/Optical use-case application.',
)
