COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//apps/optical-model:onos-apps-optical-model',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Packet/Optical Use-Case App',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'Packet/Optical use-case application.',
    required_apps = [ 'org.onosproject.optical-model' ],
)
