COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//models/polatis:onos-models-polatis',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//lib:onos-yang-model',
    '//apps/optical-model:onos-apps-optical-model',
    '//incubator/api:onos-incubator-api',
]

APPS = [
    'org.onosproject.netconf',
    'org.onosproject.models.common',
    'org.onosproject.models.polatis',
    'org.onosproject.optical-model',
    'org.onosproject.faultmanagement',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//utils/osgi:onlab-osgi-tests',
]

BUNDLES = [
    ':onos-drivers-polatis-netconf',
    '//drivers/utilities:onos-drivers-utilities',
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app(
    app_name = 'org.onosproject.drivers.polatis.netconf',
    title = 'Polatis Device Drivers',
    category = 'Drivers',
    url = 'http://www.polatis.com',
    description = 'ONOS Polatis Device Drivers application.',
    included_bundles = BUNDLES,
    required_apps = APPS
)
