COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:KRYO',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
    '//core/store/serializers:onos-core-serializers',
    '//apps/route-service/api:onos-apps-route-service-api',
    '//apps/routing/fpm/api:onos-apps-routing-fpm-api',
]

TEST_DEPS = [
    '//lib:TEST',
    '//apps/route-service/api:onos-apps-route-service-api-tests',
    '//core/api:onos-api-tests',
]

BUNDLES = [
    '//apps/dhcprelay:onos-apps-dhcprelay',
    '//apps/routing/fpm/api:onos-apps-routing-fpm-api',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
    app_name = 'org.onosproject.dhcprelay',
    title = 'DHCP Relay Agent',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'DHCP Relay Agent Application.',
    required_apps = [ 'org.onosproject.route-service' ],
    included_bundles = BUNDLES,
)
