BUNDLES = [
    '//apps/dhcprelay/web:onos-apps-dhcprelay-web',
    '//apps/dhcprelay/app:onos-apps-dhcprelay-app',
]

onos_app (
    app_name = 'org.onosproject.dhcprelay',
    title = 'DHCP Relay Agent',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'DHCP Relay Agent Application.',
    required_apps = [
        'org.onosproject.route-service',
        'org.onosproject.fpm',
    ],
    included_bundles = BUNDLES,
)
