COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/api:onos-incubator-api',
]

osgi_jar (
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.dhcprelay',
    title = 'DHCP Relay Agent App',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'DHCP Relay Agent Application.',
)
