BUNDLES = [
    "//apps/tunnel/api:onos-apps-tunnel-api",
    "//apps/tetunnel/api:onos-apps-tetunnel-api",
    "//apps/tetunnel/app:onos-apps-tetunnel-app",
]

onos_app(
    app_name = "org.onosproject.tetunnel",
    category = "Traffic Engineering",
    description = "Application to create and manage TE tunnels.",
    included_bundles = BUNDLES,
    required_apps = ["org.onosproject.tetopology"],
    title = "TE Tunnel Core",
    url = "http://onosproject.org",
)
