COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    title = 'Path Visualization',
    category = 'GUI',
    url = 'http://onosproject.org',
    description = 'Extends the GUI topology view by adding an overlay that allows the operator ' +
        'to visualize topology paths using various forms of path-finding algorithms such as ' +
        'the Dijkstra shortest path using default link metric (ONOS default), using geographic ' +
        'distances, disjoint paths, etc.',
)
