SRC_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:METRICS',
    '//incubator/api:onos-incubator-api',
    '//core/api:onos-api',
]

TEST_DEPS = [
    '//lib:TEST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    name = 'onos-core-common',
    deps = SRC_DEPS,
    test_deps = TEST_DEPS,
    visibility = ['PUBLIC'],
)
