COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:openflowj',
    '//protocols/openflow/api:onos-protocols-openflow-api',
    '//apps/optical-model:onos-apps-optical-model',
]

APPS = [
    'org.onosproject.drivers.optical',
    'org.onosproject.optical-model',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//utils/osgi:onlab-osgi-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.polatis.openflow',
    title = 'Polatis OpenFlow Device Drivers',
    category = 'Drivers',
    url = 'http://www.polatis.com',
    description = 'ONOS Polatis OpenFlow Device Drivers application.',
    required_apps = APPS
)

