COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/netconf/api:onos-protocols-netconf-api',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    title = 'Cisco device drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS Cisco device drivers application.',
    required_apps = [ 'org.onosproject.netconf' ],
)
