COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//providers/lldpcommon:onos-providers-lldpcommon',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

BUNDLES = [
    '//providers/lldpcommon:onos-providers-lldpcommon',
    '//providers/netcfglinks:onos-providers-netcfglinks',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
    app_name = 'org.onosproject.netcfglinksprovider',
    title = 'Network Config Link Provider',
    category = 'Provider',
    url = 'http://onosproject.org',
    description = 'Allows operator to prescribe information about known infrastructure links and ' +
        'their state using the network configuration subsystem. Such information takes precedence ' +
        'over information discovered through other link discovery providers.',
    included_bundles = BUNDLES,
)
