COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    title = 'Event History',
    category = 'Test Utility',
    url = 'http://onosproject.org',
    description = 'Allows recording and tracking of otherwise ephemeral ONOS core events. ' +
        'It is primarily aimed for supporting various system tests and to assure that expected ' +
        'events are raised and broadcast to applications that have requested them.',
)
