COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:KRYO',
    '//core/store/serializers:onos-core-serializers',
    '//apps/mcast/api:onos-apps-mcast-api'
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//utils/osgi:onlab-osgi-tests',
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
