COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:javax.ws.rs-api',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'XOS Client App',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'XOS client service',
)
