COMPILE_DEPS = CORE_DEPS + [
    "//incubator/api:onos-incubator-api",
    "//protocols/netconf/api:onos-protocols-netconf-api",
    "//protocols/netconf/ctl:onos-protocols-netconf-ctl",
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
