COMPILE_DEPS = CORE_DEPS + JACKSON + [
    "//incubator/api:onos-incubator-api",
    "//apps/faultmanagement/fmmgr:onos-apps-faultmanagement-fmmgr",
    "//cli:onos-cli",
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
