APPS = [
    # dynamic config
    'org.onosproject.config',
]

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//apps/config:onos-apps-config',
    '//lib:onos-yang-model',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Dynamic Configuration Synchronizer',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'Application to support the Dynamic configuration service.',
    required_apps = APPS,
)
