COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:javax.ws.rs-api',
    '//utils/rest:onlab-rest',
    '//apps/segmentrouting/app:onos-apps-segmentrouting-app',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    web_context = '/onos/segmentrouting',
    api_title = 'Segment Routing REST API',
    api_version = '1.0',
    api_description = 'REST API for Segment Routing Application',
    api_package = 'org.onosproject.segmentrouting.web',
)
