GRPC_VER = '1.3.1'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    ':onos-incubator-protobuf-services-nb-proto',
    '//incubator/protobuf/models:onos-incubator-protobuf-models-proto',
    '//incubator/protobuf/models:onos-incubator-protobuf-models',
    '//lib:protobuf-java-3.2.0',
    '//lib:GRPC_1.3',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//lib:grpc-protobuf-lite-' + GRPC_VER,
    '//incubator/protobuf/api:onos-grpc-api'
]

TEST_DEPS = [
    '//lib:TEST',
    '//lib:TEST_ADAPTERS',
]

GRPC_DEPS = [
    '//lib:GRPC_1.3',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//incubator/protobuf/models:onos-incubator-protobuf-models-proto',
    '//lib:protobuf-java-3.2.0',
    '//lib:guava',
]

BUNDLES = [
    '//incubator/protobuf/models:onos-incubator-protobuf-models',
    '//incubator/protobuf/models:onos-incubator-protobuf-models-proto',
    ':onos-incubator-protobuf-services-nb',
    ':onos-incubator-protobuf-services-nb-proto',
    '//lib:protobuf-java-3.2.0',
    '//lib:guava',
    '//lib:grpc-core-' + GRPC_VER,
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//lib:grpc-protobuf-' + GRPC_VER,
    '//lib:grpc-stub-' + GRPC_VER,
    '//lib:grpc-netty-' + GRPC_VER,
    '//lib:grpc-auth-' + GRPC_VER,
    '//lib:grpc-context-' + GRPC_VER,
    '//lib:google-truth-0.28',
    '//core/api:onos-api',
    '//lib:netty-transport',
    '//lib:netty-buffer',
    '//lib:netty-resolver',
    '//lib:netty-common',
    '//lib:netty-codec',
    '//lib:netty-handler',
    '//lib:netty-codec-http2',
    '//lib:netty-codec-http',
    "//lib:google-instrumentation-0.3.0",
]

grpc_jar(
    name = 'onos-incubator-protobuf-services-nb-proto',
    deps = GRPC_DEPS,
    # FIXME should not be manually building absolute path
    # come up with glob(..) equivalent in BUCK which can handle directory
    proto_paths = ["$ONOS_ROOT/incubator/protobuf/services/nb/src/main/proto",
        "$ONOS_ROOT/incubator/protobuf/models/src/main/proto"]
)

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    visibility = ['PUBLIC'],
)

onos_app (
    title = 'Grpc Northbound Service',
    app_name = "org.onosproject.grpc.nb.service",
    category = 'Utility',
    url = 'http://onosproject.org',
    included_bundles = ['//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
            '//lib:google-instrumentation-0.3.0'],
    description = 'gRPC northbound services used to provide fine-grained access to ONOS native northbound interface from off-platform applications',
)
