COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
    '//utils/rest:onlab-rest',
    '//apps/route-service/api:onos-apps-route-service-api',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.routescale',
    title = 'Route and Flow Scalability Test',
    category = 'Test Utility',
    url = 'http://onosproject.org',
    description = 'Route and flow scalability test facility.',
    required_apps = [ 'org.onosproject.route-service' ],
)
