SRC = 'src/main/java/org/onosproject/**/'
TEST = 'src/test/java/org/onosproject/**/'

CURRENT_NAME = 'onos-app-fwd'
CURRENT_TARGET = ':' + CURRENT_NAME

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
]

TEST_DEPS = [
    '//lib:TEST',
]

osgi_jar(
    name = CURRENT_NAME,
    srcs = glob([SRC + '/*.java']),
    deps = COMPILE_DEPS,
    visibility = ['PUBLIC'],
)

java_test(
    name = 'tests',
    srcs = glob([TEST + '/*.java']),
    deps = COMPILE_DEPS +
           TEST_DEPS +
           [CURRENT_TARGET],
    source_under_test = [CURRENT_TARGET],
)

BUNDLES = [
    (CURRENT_TARGET, ONOS_GROUP_ID + ':' + CURRENT_NAME + ':' + ONOS_VERSION),
]

onos_app(
    app_name = 'org.onosproject.fwd',
    title = 'Reactive Forwarding App',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'Reactive forwarding application using flow subsystem.',
    included_bundles = BUNDLES,
)