COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
]

osgi_jar(
    deps = COMPILE_DEPS,
)

onos_app(
    title = 'Reactive Forwarding App',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'Reactive forwarding application using flow subsystem.',
)