COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:minimal-json',
    '//apps/pi-demo/common:onos-apps-pi-demo-common',
    '//pipelines/basic:onos-pipelines-basic',
]

osgi_jar (
    deps = COMPILE_DEPS,
)

BUNDLES = [
    '//apps/pi-demo/common:onos-apps-pi-demo-common',
    '//apps/pi-demo/ecmp:onos-apps-pi-demo-ecmp',
]

onos_app (
    app_name = 'org.onosproject.pi-ecmp',
    title = 'PI Demo ECMP Fabric',
    category = 'Traffic Engineering',
    url = 'http://onosproject.org',
    description = 'Provides ECMP support for a 2-stage clos fabric topology of PI-enabled devices',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.pipelines.basic'
    ]
)
