COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/api:onos-incubator-api',
    '//apps/routing-api:onos-apps-routing-api',
]

BUNDLES = [
    '//apps/routing-api:onos-apps-routing-api',
    '//apps/routing/common:onos-apps-routing-common',
    '//apps/bgprouter:onos-apps-bgprouter',
]

osgi_jar (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'BGP Router App',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'BGP router application.',
    included_bundles = BUNDLES,
    required_apps = [ 'org.onosproject.fibinstaller' ],
)
