GRPC_VER = '1.3.0'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/p4runtime/api:onos-protocols-p4runtime-api',
    '//incubator/bmv2/model:onos-incubator-bmv2-model',
    '//drivers/default:onos-drivers-default',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//lib:grpc-netty-' + GRPC_VER,
]

BUNDLES = [
    ':onos-drivers-bmv2',
    '//incubator/bmv2/model:onos-incubator-bmv2-model',
    '//drivers/default:onos-drivers-default',
]

osgi_jar(
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.drivers.bmv2',
    title = 'BMv2 Device Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS BMv2 device drivers application.',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.generaldeviceprovider',
        'org.onosproject.protocols.p4runtime'
    ],
)
