COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
    import_packages = '*,org.onosproject.cli.net',
)

onos_app (
    title = 'Null Provider Suite',
    category = 'Test Utility',
    url = 'http://onosproject.org',
    description = 'Suite of device, link, host, flow and packet providers that allow the operator ' +
        'to test ONOS against completely fictional network topology. This is useful for conducting ' +
        'ONOS core performance tests and for developing features that require only control plane ' +
        '- and not data plane - functionality. ',
)
