BUNDLES = [
    '//apps/imr/api:onos-apps-imr-api',
    '//apps/imr/app:onos-apps-imr-app',
]

onos_app (
    title = 'Intent Monitoring and Rerouting',
    category = 'Traffic Engineering',
    url = 'http://onosproject.org', # link alla wiki su wiki.onosproject.org
    description = 'Intent Monitoring and Rerouting application.',
    included_bundles = BUNDLES,
)
