BUNDLES = [
    "//apps/imr/api:onos-apps-imr-api",
    "//apps/imr/app:onos-apps-imr-app",
]

onos_app(
    category = "Traffic Engineering",
    description = "Intent Monitoring and Rerouting application.",
    included_bundles = BUNDLES,
    title = "Intent Monitoring and Rerouting",
    url = "http://onosproject.org",  # link alla wiki su wiki.onosproject.org
)
