BUNDLES = [
    '//apps/simplefabric/api:onos-apps-simplefabric-api',
    '//apps/simplefabric/app:onos-apps-simplefabric-app',
]

onos_app (
    title = 'SONA SimpleFabric',
    category = 'Traffic Engineering',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
    description = 'SONA Simple Fabric Application',
    required_apps = [ 'org.onosproject.openflow-base', 'org.onosproject.lldpprovider', 'org.onosproject.hostprovider' ],
)