COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:concurrent-trees',
    '//lib:javax.ws.rs-api',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
    '//utils/rest:onlab-rest',
]

BUNDLES = [
    '//apps/simplefabric:onos-apps-simplefabric',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    web_context = '/onos/v1/simplefabric',
)

onos_app (
  title = 'SimpleFabric',
  category = 'Traffic Engineering',
  url = 'http://onosproject.org',
  included_bundles = BUNDLES,
  description = 'Simple Fabric application',
  required_apps = [ 'org.onosproject.openflow-base', 'org.onosproject.lldpprovider', 'org.onosproject.hostprovider' ],
)
