BUNDLES = [
    "//apps/simplefabric/api:onos-apps-simplefabric-api",
    "//apps/simplefabric/app:onos-apps-simplefabric-app",
]

onos_app(
    category = "Traffic Engineering",
    description = "SONA Simple Fabric Application",
    included_bundles = BUNDLES,
    required_apps = [
        "org.onosproject.openflow-base",
        "org.onosproject.lldpprovider",
        "org.onosproject.hostprovider",
        "org.onosproject.route-service",
    ],
    title = "SONA SimpleFabric",
    url = "http://onosproject.org",
)
