GRPC_VER = '1.3.1'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//protocols/grpc/api:onos-protocols-grpc-api',
]

TEST_DEPS = [
    '//core/api:onos-api-tests',
    '//lib:TEST',
    '//protocols/p4runtime/api:onos-protocols-p4runtime-api',
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
