COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/grpc-dependencies:grpc-core-repkg-1.3.0',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]


osgi_jar_with_tests(
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)