COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.servicemix.bundles.dom4j',
    '//models/l3vpn:onos-models-l3vpn',
    '//models/huawei:onos-models-huawei',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//apps/l3vpn:onos-apps-l3vpn',
    '//apps/config:onos-apps-config',
    '//lib:onos-yang-model',
    '//lib:onos-yang-runtime',
    '//apps/yang:onos-apps-yang',
]

APPS = [
    'org.onosproject.yang',
    'org.onosproject.yang-gui',
    'org.onosproject.config',
    'org.onosproject.restconf',
    'org.onosproject.yms',
    'org.onosproject.protocols.restconfserver',
    'org.onosproject.netconf',
    'org.onosproject.netconfsb',
    'org.onosproject.models.l3vpn',
    'org.onosproject.l3vpn',
    'org.onosproject.models.huawei',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//utils/osgi:onlab-osgi-tests',
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app(
    app_name = 'org.onosproject.drivers.huawei',
    title = 'Huawei Device Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS Huawei Device Drivers application.',
    required_apps = APPS
)