APPS = [
  'org.onosproject.yang',
  'org.onosproject.yang-gui',
  'org.onosproject.config',
  'org.onosproject.restconf',
  'org.onosproject.yms',
  'org.onosproject.protocols.restconfserver',
  'org.onosproject.netconf',
  'org.onosproject.netconfsb',
  'org.onosproject.models.l3vpn',
  'org.onosproject.l3vpn',
]

BUNDLES = [
  '//drivers/huawei/yangmodel:onos-drivers-huawei-yangmodel',
  '//drivers/huawei/driver:onos-drivers-huawei-driver',
]

onos_app(
  app_name = 'org.onosproject.drivers.huawei',
  title = 'Huawei Device Drivers',
  category = 'Drivers',
  url = 'http://onosproject.org',
  description = 'ONOS Huawei Device Drivers application.',
  included_bundles = BUNDLES,
  required_apps = APPS
)