COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/grpc-dependencies:grpc-core-repkg-1.3.1'
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    name = 'onos-grpc-api',
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    visibility = ['PUBLIC'],
)
