java_proto_library(
    name = "p4_types_java_proto",
    deps = [ "@p4lang_pi//:p4types_proto" ],
    visibility = ["//visibility:public"],
)

java_proto_library(
    name = "p4_config_java_proto",
    deps = [ "@p4lang_pi//:p4config_proto" ],
    visibility = ["//visibility:public"],
)

java_proto_library(
    name = "p4_tmp_config_java_proto",
    deps = [ "@p4lang_pi//:p4_tmp_config_proto" ],
    visibility = ["//visibility:public"],
)

java_proto_library(
    name = "p4_runtime_java_proto",
    deps = [ "@p4lang_pi//:p4_runtime_proto" ],
    visibility = ["//visibility:public"],
)

