java_proto_library(
    name = "p4_types_java_proto",
    visibility = ["//visibility:public"],
    deps = ["@p4lang_pi//:p4types_proto"],
)

java_proto_library(
    name = "p4_config_java_proto",
    visibility = ["//visibility:public"],
    deps = ["@p4lang_pi//:p4config_proto"],
)

java_proto_library(
    name = "p4_tmp_config_java_proto",
    visibility = ["//visibility:public"],
    deps = ["@p4lang_pi//:p4_tmp_config_proto"],
)

java_proto_library(
    name = "p4_runtime_java_proto",
    visibility = ["//visibility:public"],
    deps = ["@p4lang_pi//:p4_runtime_proto"],
)
