BUNDLES = [
    "//apps/k8s-node/api:onos-apps-k8s-node-api",
    "//apps/k8s-node/app:onos-apps-k8s-node-app",
]

onos_app(
    category = "Integration",
    description = "SONA Kubernetes Node Application.",
    included_bundles = BUNDLES,
    title = "Kubernetes Node Application",
    url = "https://wiki.onosproject.org/display/ONOS/SONA%3A+DC+Network+Virtualization",
)
