APPS = [
    'org.onosproject.ovsdb-base',
    'org.onosproject.ovsdbhostprovider',
]

onos_app (
    app_name = 'org.onosproject.ovsdb',
    title = 'OVSDB Southbound Meta App',
    category = 'Provider',
    url = 'http://onosproject.org',
    description = 'ONOS OVSDB southbound meta application',
    included_bundles = [ '//utils/osgi:onlab-osgi' ],  # FIXME to allow hollow oar files
    required_apps = APPS,
)
