BUNDLES = [
    '//providers/ovsdb/device:onos-ovsdb-provider-device',
    '//providers/ovsdb/host:onos-ovsdb-provider-host',
    '//providers/ovsdb/tunnel:onos-ovsdb-provider-tunnel',
]

APPS = [
    'org.onosproject.ovsdb-base',
    'org.onosproject.ovsdbhostprovider',
]

onos_app (
  title = 'OVSDB Southbound Meta App',
  description = 'ONOS fault management application',
  category = 'Provider',
  url = 'https://wiki.onosproject.org/display/ONOS/Fault+Management',
  included_bundles = BUNDLES,
  required_apps = APPS,
)
