COMPILE_DEPS = [
    '//lib:CORE_DEPS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    title = 'YANG Runtime GUI',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'YANG Runtime GUI application for visualization of registered YANG models.',
)
