COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:javax.ws.rs-api',
    '//utils/rest:onlab-rest',
    '//apps/optical-model:onos-apps-optical-model'
]

APPS = [
    'org.onosproject.optical-model',
]

TEST_DEPS = [
    '//lib:TEST_REST',
    '//utils/osgi:onlab-osgi-tests',
    '//web/api:onos-rest-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    web_context = '/onos/optical',
    api_title = 'Optical Network Model REST API',
    api_version = '1.0',
    api_description = 'REST API for Optical Model',
    api_package = 'org.onosproject.net.optical.rest'
)

onos_app (
    title = 'Optical Network Model REST API',
    category = 'Optical',
    url = 'http://onosproject.org',
    description = 'This application provides REST support for optical network model.',
    required_apps = APPS
)
