COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//models/ietf:onos-models-ietf',
]

APPS = [
    'org.onosproject.models.ietf',
]

yang_model(
  app_name = 'org.onosproject.models.openconfig',
  title = 'OpenConfig YANG Models',
  custom_registrator = True,
  deps = COMPILE_DEPS,
  required_apps = APPS,
)
