BUNDLES = [
    '//providers/netconf/device:onos-providers-netconf-device',
    '//providers/netconf/alarm:onos-providers-netconf-alarm',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//protocols/netconf/ctl:onos-protocols-netconf-ctl',
    '//lib:sshd-core',
]

EXCLUDED_BUNDLES = [
    '//lib:ganymed-ssh2',
]

onos_app (
    title = 'NETCONF Provider',
    category = 'Provider',
    url = 'https://wiki.onosproject.org/display/ONOS/NETCONF',
    included_bundles = BUNDLES,
    excluded_bundles = EXCLUDED_BUNDLES,
    description = 'Provides means for ONOS to discover and trigger the initial handshake procedure ' +
        'with NETCONF from information given by network configuration.' +
        'Also provides capabilities for receiving asynchronous alarm notifications from devices.',
    required_apps = [ 'org.onosproject.faultmanagement'],
)


