BUNDLES = [
    "//apps/restconf/api:onos-apps-restconf-api",
    "//apps/restconf/utils:onos-apps-restconf-utils",
    "//apps/restconf/restconfmgr:onos-apps-restconf-restconfmgr",
]

APPS = [
    "org.onosproject.yang",
    "org.onosproject.config",
]

onos_app(
    app_name = "org.onosproject.restconf",
    category = "Utility",
    included_bundles = BUNDLES,
    required_apps = APPS,
    title = "RESTCONF Application Module",
    url = "http://onosproject.org",
)
