COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/bgp/bgpio:onos-protocols-bgp-bgpio',
    '//core/api:onos-api',
    '//lib:io_netty_netty',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
