COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:ONOS_YANG',
    '//lib:javax.ws.rs-api',
    '//drivers/utilities:onos-drivers-utilities',
    '//drivers/netconf:onos-drivers-netconf',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//protocols/netconf/ctl:onos-protocols-netconf-ctl',
    '//models/common:onos-models-common',
    '//models/ciena/waveserverai:onos-models-ciena-waveserverai',
    '//apps/optical-model:onos-apps-optical-model',
    '//drivers/optical:onos-drivers-optical',
]
TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//drivers/netconf:onos-drivers-netconf-tests',
    '//utils/osgi:onlab-osgi-tests',
]

BUNDLES = [
    ':onos-drivers-ciena-waveserverai',
    '//drivers/utilities:onos-drivers-utilities',
    '//drivers/netconf:onos-drivers-netconf',
]

REQUIRED_APPS = [
    'org.onosproject.yang',
    'org.onosproject.optical-model',
    'org.onosproject.drivers.optical',
    'org.onosproject.models.ciena.waveserverai',
    'org.onosproject.netconf',
    'org.onosproject.netconfsb',
    'org.onosproject.drivers.netconf',
    'org.onosproject.linkdiscovery',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.ciena.waveserverai',
    title = 'Ciena Waveserver Ai Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'Adds support for Ciena Waveserver Ai devices.',
    required_apps = REQUIRED_APPS,
    included_bundles = BUNDLES,
)
