COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//drivers/p4runtime:onos-drivers-p4runtime',
]

BUNDLES = [
    ':onos-drivers-mellanox',
]

osgi_jar(
    deps = COMPILE_DEPS,
)

onos_app(
    app_name = 'org.onosproject.drivers.mellanox',
    title = 'Mellanox Drivers',
    category = 'Drivers',
    url = 'https://wiki.onosproject.org/x/aAZkAQ',
    description = 'Adds support for Mellanox Spectrum-based devices using P4Runtime',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.drivers.p4runtime',
        'org.onosproject.pipelines.fabric',
    ],
)
