COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//models/common:onos-models-common',
]

APPS = [
    'org.onosproject.models.common',
]

yang_model(
    app_name = 'org.onosproject.models.l3vpn',
    title = 'L3VPN YANG Models',
    custom_registrator = True,
    deps = COMPILE_DEPS,
    required_apps = APPS,
)
