COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:onos-yang-model',
    '//lib:onos-yang-runtime',
    '//models/tapi:onos-models-tapi',
    '//models/openconfig:onos-models-openconfig',
    '//apps/yang:onos-apps-yang',
    '//apps/config:onos-apps-config',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

APPS = [
    'org.onosproject.yang',
    'org.onosproject.models.tapi',
    'org.onosproject.models.openconfig',
]

# TODO probably bucklet, etc. should escape title & description
onos_app (
    app_name = 'org.onosproject.odtn-api',
    title = 'ODTN API &amp; Utilities Application',
    category = 'Traffic Engineering',
    url = 'http://onosproject.org',
    description = 'ODTN API &amp; Utilities Application',
    required_apps = APPS,
)
