COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/bgp/api:onos-protocols-bgp-api',
    '//protocols/bgp/bgpio:onos-protocols-bgp-bgpio',
    '//incubator/store:onos-incubator-store',
    '//incubator/api:onos-incubator-api',
    '//apps/pcep-api:onos-apps-pcep-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
