COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/bgp/api:onos-bgp-api',
    '//protocols/bgp/bgpio:onos-bgpio',
    '//incubator/store:onos-incubator-store',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
