COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:ONOS_YANG',
    '//lib:onos-yang-runtime',
    '//apps/yang:onos-apps-yang',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    title = 'YANG Runtime GUI',
    category = 'GUI',
    url = 'http://onosproject.org',
    description = 'Adds GUI extension that allows the operator to view the list of currently ' +
        'registered YANG models, and their YANG sources. It also provides means for compiling ' +
        'source YANG files (*.yang, *.zip, *.jar) on the fly and directly from the GUI using ' +
        'drag-n-drop.<p/>User can simply compress a set of YANG source files and drop it on the ' +
        'YANG Models GUI view to automatically compile and then register the compiled YANG models.',
    required_apps = [ 'org.onosproject.yang' ],
)
