PROTOBUF_VER = '3.2.0'
GRPC_VER = '1.3.1'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:KRYO',
    '//protocols/grpc/api:onos-protocols-grpc-api',
    '//protocols/grpc/proto:onos-protocols-grpc-proto',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//lib:grpc-netty-' + GRPC_VER,
    '//lib:protobuf-java-' + PROTOBUF_VER,
    '//lib:grpc-stub-' + GRPC_VER,
    '//core/store/serializers:onos-core-serializers',
    '//protocols/gnmi/stub:onos-protocols-gnmi-stub',
]

BUNDLES = [
    ':onos-drivers-gnmi',
]

osgi_jar (
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.drivers.gnmi',
    title = 'gNMI Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'Adds support for devices using gNMI protocol based on ' +
    ' openconfig models: http://openconfig.net/ .',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.generaldeviceprovider',
        'org.onosproject.protocols.grpc',
        'org.onosproject.protocols.gnmi'
    ],
)