COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//incubator/api:onos-incubator-api'
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
  title = 'Link Properties',
  description = 'Shows more link properties',
  category = 'Monitoring',
  url = 'https://onosproject.org/',
)
