BUNDLES = [
    "//apps/inbandtelemetry/api:onos-apps-inbandtelemetry-api",
    "//apps/inbandtelemetry/impl:onos-apps-inbandtelemetry-impl",
    "//apps/inbandtelemetry/app:onos-apps-inbandtelemetry-app",
]

onos_app(
    app_name = "org.onosproject.inbandtelemetry",
    category = "Monitoring",
    description = "Provides managements of INT-capable devices. Specifies flows to enable INT and" +
                  "types of metadata to collect. Sets up INT-related information.",
    included_bundles = BUNDLES,
    title = "P4 In-band Network Telemetry Service",
    url = "http://onosproject.org",
)
