COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:openflowj',
    '//protocols/openflow/api:onos-protocols-openflow-api',
    '//lib:NETTY',
    '//lib:netty-buffer',
    '//lib:netty-codec',
    '//lib:netty-common',
    '//lib:netty-handler',
    '//lib:netty-transport',
    '//lib:netty-transport-native-epoll',
    '//lib:JACKSON',
]

TEST_DEPS = [
    '//lib:TEST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
