GRPC_VER = '1.3.1'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//lib:GRPC_1.3',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//incubator/protobuf/api:onos-grpc-api'
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Grpc Service Registry',
    app_name = "org.onosproject.grpc.registry",
    included_bundles = ['//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
        '//lib:google-instrumentation-0.3.0'],
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'Service providing connections for remote apps communicating with the ONOS core via gRPC.',
)
