BUNDLES = [
    '//apps/openstacknode/api:onos-apps-openstacknode-api',
    '//apps/openstacknode/app:onos-apps-openstacknode-app',
]

onos_app (
    title = 'OpenStack Node Bootstrap',
    category = 'Integration',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
    description = 'SONA Openstack Node Bootstrap Application.',
    required_apps = [ 'org.onosproject.ovsdb-base', 'org.onosproject.drivers.ovsdb' ]
)
