BUNDLES = [
    "//apps/openstacknode/api:onos-apps-openstacknode-api",
    "//apps/openstacknode/app:onos-apps-openstacknode-app",
]

onos_app(
    category = "Integration",
    description = "SONA Openstack Node Bootstrap Application.",
    included_bundles = BUNDLES,
    required_apps = [
        "org.onosproject.ovsdb-base",
        "org.onosproject.drivers.ovsdb",
    ],
    title = "OpenStack Node Bootstrap",
    url = "http://onosproject.org",
)
