BUNDLES = [
    '//protocols/ovsdb/rfc:onos-protocols-ovsdb-rfc',
    '//protocols/ovsdb/api:onos-protocols-ovsdb-api',
    '//protocols/ovsdb/ctl:onos-protocols-ovsdb-ctl',

    '//providers/ovsdb/tunnel:onos-providers-ovsdb-tunnel',
    '//providers/ovsdb/device:onos-providers-ovsdb-device',
]

onos_app (
    app_name = 'org.onosproject.ovsdb-base',
    title = 'OVSDB Provider',
    category = 'Provider',
    url = 'http://onosproject.org',
    description = 'ONOS OVSDB provider.',
    included_bundles = BUNDLES,
)
