COMPILE_DEPS = [
    '//lib:CORE_DEPS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Host Mobility App',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'Host mobility application.',
)
