COMPILE_DEPS = CORE_DEPS

osgi_jar(
    visibility = ["//visibility:public"],
    deps = COMPILE_DEPS,
)

onos_app(
    title = "Host Mobility",
    category = "Utility",
    url = "http://onosproject.org",
    description = "Host mobility application.",
)
