COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//apps/tetunnel/api:onos-apps-tetunnel-api',

 ]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

