COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:jersey-client',
    '//lib:httpclient-osgi',
    '//lib:httpcore-osgi',
    '//lib:javax.ws.rs-api',
    '//protocols/bgp/api:onos-protocols-bgp-api',
    '//protocols/bgp/bgpio:onos-protocols-bgp-bgpio',
    '//lib:io_netty_netty_common',
    '//lib:io_netty_netty',
    '//lib:org.osgi.compendium',
    '//lib:org.apache.felix.scr.annotations',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
