BUNDLES = [
    "//apps/flowspec-api/flowapi:onos-apps-flowspec-api-flowapi",
]

onos_app(
    description = "ONOS framework applications",
    included_bundles = BUNDLES,
    title = "Flowspec API",
    url = "http://onosproject.org",
)
