COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:jersey-client',
    '//lib:jersey-server',
    '//lib:javax.ws.rs-api',
    '//utils/rest:onlab-rest',
    '//core/store/serializers:onos-core-serializers',
    '//protocols/restconf/server/api:onos-protocols-restconf-server-api',
    '//protocols/restconf/server/utils:onos-protocols-restconf-server-utils',
    '//apps/yms/api:onos-apps-yms-api',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
