GRPC_VER = '1.3.1'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:minimal-json',
    '//protocols/p4runtime/api:onos-protocols-p4runtime-api',
    '//drivers/p4runtime:onos-drivers-p4runtime',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//lib:grpc-netty-' + GRPC_VER,
]

BUNDLES = [
    ':onos-drivers-barefoot',
]

osgi_jar(
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.drivers.barefoot',
    title = 'Barefoot Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'Adds support for Barefoot-based devices',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.drivers.p4runtime',
    ],
)
