COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:KRYO',
    '//protocols/p4runtime/model:onos-protocols-p4runtime-model',
    '//protocols/p4runtime/api:onos-protocols-p4runtime-api',
    '//pipelines/basic:onos-pipelines-basic',
    '//core/store/serializers:onos-core-serializers',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

BUNDLES = [
    '//pipelines/fabric:onos-pipelines-fabric',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app(
    app_name = 'org.onosproject.pipelines.fabric',
    title = 'Fabric Pipeline',
    category = 'Pipeline',
    url = 'http://onosproject.org',
    description = 'Provides pipelines with CORD fabric underlay support.',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.drivers.p4runtime',
        'org.onosproject.pipelines.basic',
    ]
)
