COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
    '//core/store/serializers:onos-core-serializers',
    '//lib:KRYO',
]
osgi_jar (
    deps = COMPILE_DEPS,
)
onos_app (
    title = 'Cluster HA Test',
    category = 'Test Utility',
    url = 'http://onosproject.org',
    description = 'Test for ONOS Cluster HA',
)
