BUNDLES = [
    '//apps/faultmanagement/fmcli:onos-apps-faultmanagement-fmcli',
    '//apps/faultmanagement/fmgui:onos-apps-faultmanagement-fmgui',
    '//apps/faultmanagement/fmmgr:onos-apps-faultmanagement-fmmgr',
    '//apps/faultmanagement/fmweb:onos-apps-faultmanagement-fmweb',
]

onos_app(
    title = 'Fault Management',
    origin = 'BTI Systems',
    description = 'Provides managements of alarms. Stores retrieved alarms from devices. ' +
        'Offers CLI, UI and REST integration to obtain and display them from ONOS.',
    category = 'Monitoring',
    url = 'https://wiki.onosproject.org/display/ONOS/Fault+Management',
    included_bundles = BUNDLES,
)
