COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//lib:JACKSON',
  '//lib:javax.ws.rs-api',
  '//utils/rest:onlab-rest',
  '//core/store/serializers:onos-core-serializers',
]

TEST_DEPS = [
  '//lib:TEST_REST',
  '//lib:jersey-server',
]

osgi_jar_with_tests (
  deps = COMPILE_DEPS,
  test_deps = TEST_DEPS,
  web_context = '/onos/cord-support',
  api_title = 'CORD Support',
  api_version = '1.0',
  api_description = 'REST API for CORD inquiry to ONOS topology',
  api_package = 'org.onosproject.cordsupport',
)

onos_app (
  title = 'CORD Support',
  category = 'Integration',
  url = 'http://onosproject.org',
  description = 'CORD Support application.',
)
