COMPILE_DEPS = [
    '//lib:CORE_DEPS',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

#This is just a dummy placeholder while the code is being moved.
osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
    app_name = 'org.onosproject.drivers.microsemi',
    title = 'Microsemi Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'A dummy placeholder while code is being moved.',
    required_apps = APPS,
)