BUNDLES = [
    '//lib:kafka-clients',
    '//lib:protobuf-java-3.2.0',
    '//incubator/protobuf/models:onos-incubator-protobuf-models',
    '//incubator/protobuf/models:onos-incubator-protobuf-models-proto',
    '//apps/kafka-integration/api:onos-apps-kafka-integration-api',
    '//apps/kafka-integration/app:onos-apps-kafka-integration-app',
]

onos_app (
  title = 'Kafka Integration',
  category = 'Integration',
  url = 'http://onosproject.org',
  description = 'Provides integration of ONOS and Kafka message bus so that internal ONOS events ' +
    'can be broadcast over the Kafka message bus to off-platform applications.',
  included_bundles = BUNDLES,
)
