APPS = [
    'org.onosproject.configsync',
    'org.onosproject.yang',
    'org.onosproject.netconf',
]

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:onos-yang-model',
    '//lib:onos-yang-runtime',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//apps/config:onos-apps-config',
    '//apps/configsync:onos-apps-configsync',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
    title = 'Dynamic Configuration Synchronizer for NETCONF',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'Application to support the Dynamic configuration service.',
    required_apps = APPS,
)
