COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//apps/mappingmanagement/api:onos-apps-mappingmanagement-api',
    '//core/store/serializers:onos-core-serializers',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//utils/osgi:onlab-osgi-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
