COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//lib:jackson-databind',
    '//lib:jackson-annotations',
    '//lib:osgi-core',
    '//lib:org.apache.karaf.shell.console',
    '//lib:org.apache.felix.scr.annotations',
    '//lib:io_netty_netty',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

