COMPILE_DEPS = CORE_DEPS + CLI + [
    "//apps/network-troubleshoot/api:onos-apps-network-troubleshoot-api",
]

osgi_jar_with_tests(
    import_packages = "*,org.onosproject.cli.net",
    deps = COMPILE_DEPS,
)
