COMPILE_DEPS = CORE_DEPS + CLI + [
    "//apps/network-troubleshoot/api:onos-apps-network-troubleshoot-api",
]

osgi_jar_with_tests(
    karaf_command_packages = ["org.onosproject.fnl.cli"],
    deps = COMPILE_DEPS,
)
