COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:openflowj',
    '//drivers/default:onos-drivers-default',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/openflow/api:onos-protocols-openflow-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.corsa',
    title = 'Corsa device drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS Corsa device drivers application.',
    required_apps = [ 'org.onosproject.openflow' ],
)
