BUNDLES = [
    "//providers/general/device:onos-providers-general-device",
]

onos_app(
    app_name = "org.onosproject.generaldeviceprovider",
    category = "Provider",
    description = "General device southbound providers.",
    included_bundles = BUNDLES,
    required_apps = ["org.onosproject.protocols.gnmi"],
    title = "General Device Provider",
    url = "http://onosproject.org",
)
