osgi_jar_with_tests(
    deps = CORE_DEPS,
)

onos_app(
    category = "Test Utility",
    description = "Network configuration monitor test application.",
    title = "Network Configuration Monitor Test",
    url = "http://onosproject.org",
)
