COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/api:onos-incubator-api',
    '//protocols/snmp/api:onos-protocols-snmp-api',
    '//lib:org.apache.servicemix.bundles.snmp4j',
    '//lib:snmp-core',
    '//lib:bti7000',
    '//lib:mibs-net-snmp',
    '//lib:mibs-rfc',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

