COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//core/common:onos-core-common',
    '//incubator/api:onos-incubator-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//core/common:onos-core-common-tests',
    '//incubator/store:onos-incubator-store',
    '//core/store/serializers:onos-core-serializers',
    '//lib:concurrent-trees',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
