COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:tinder-xmpp',
    '//protocols/xmpp/core/api:onos-protocols-xmpp-core-api',
    '//protocols/xmpp/core/ctl:onos-protocols-xmpp-core-ctl',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
    app_name = 'org.onosproject.xmpp.device',
    title = 'XMPP Device Provider',
    category = 'Provider',
    url = 'https://wiki.onosproject.org/display/ONOS/XMPP+as+SBI',
    description = 'XMPP protocol southbound provider.',
    required_apps = [
        'org.onosproject.protocols.xmpp',
    ]
)