COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//lib:JACKSON',
    '//lib:io_netty_netty_transport',
    '//protocols/ovsdb/rfc:onos-protocols-ovsdb-rfc',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

