BUNDLES = [
    "@tinder_xmpp//jar",
    "@org_apache_servicemix_bundles_dom4j//jar",
    "@netty_common//jar",
    "@netty_transport//jar",
    "@netty_buffer//jar",
    "@netty_codec//jar",
    "@stax2_api//jar",
    "@aalto_xml//jar",
    "@concurrent_hashmap//jar",
    "@gnu_idn//jar",
    "//protocols/xmpp/core/api:onos-protocols-xmpp-core-api",
    "//protocols/xmpp/core/ctl:onos-protocols-xmpp-core-ctl",
]

onos_app(
    app_name = "org.onosproject.protocols.xmpp",
    category = "Protocol",
    description = "ONOS XMPP core protocol subsystem",
    included_bundles = BUNDLES,
    title = "XMPP Core Protocol Subsystem",
    url = "https://wiki.onosproject.org/display/ONOS/XMPP+as+SBI",
)
