COMPILE_DEPS = [
    '//lib:COMPILE',
    '//lib:NETTY',
    '//lib:METRICS',
    '//lib:KRYO',
    '//lib:netty',
    '//lib:JACKSON',
]

osgi_jar_with_tests(
    name = 'onlab-misc',
    deps = COMPILE_DEPS,
    package_name_root = 'org.onlab',
    visibility = ['PUBLIC'],
)


