COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:jersey-client',
    '//lib:javax.ws.rs-api',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
    '//utils/rest:onlab-rest',
    '//incubator/api:onos-incubator-api',
    '//core/store/serializers:onos-core-serializers'
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
    title = 'VLAN L2 Broadcast Network App',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'Application to create L2 broadcast network using VLAN.',
    required_apps = [ 'org.onosproject.intentsynchronizer' ],
)
