COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:jersey-client',
    '//lib:javax.ws.rs-api',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
    '//utils/rest:onlab-rest',
    '//incubator/api:onos-incubator-api',
    '//apps/routing-api:onos-apps-routing-api',
    '//apps/routing:onos-apps-routing',
]

BUNDLES = [
    '//apps/vpls:onos-apps-vpls',
    '//apps/routing-api:onos-apps-routing-api',
    '//apps/routing:onos-apps-routing',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
    title = 'VLAN L2 Broadcast Network App',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
    description = 'Application to create L2 broadcast network using VLAN.',
)
