COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//core/store/serializers:onos-core-serializers',
    '//apps/openstackinterface/api:onos-apps-openstackinterface-api',
    '//apps/openstacknetworking/api:onos-apps-openstacknetworking-api',
    '//apps/scalablegateway:onos-apps-scalablegateway',
    '//apps/openstacknode:onos-apps-openstacknode',
]

BUNDLES = [
    '//apps/openstacknetworking/api:onos-apps-openstacknetworking-api',
    '//apps/openstacknetworking/web:onos-apps-openstacknetworking-web',
    '//apps/openstacknetworking/routing:onos-apps-openstacknetworking-routing',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.openstackrouting',
    title = 'OpenStack Routing App',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'OpenStack routing application.',
    included_bundles = BUNDLES,
    required_apps = [ 'org.onosproject.openstackinterface', 'org.onosproject.openstacknode', 'org.onosproject.scalablegateway' ]
)
