COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//core/store/dist:onos-core-dist',
    '//core/store/serializers:onos-core-serializers',
    '//incubator/api:onos-incubator-api',
    '//lib:KRYO',
    '//lib:JACKSON',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
