COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:openflowj',
    '//protocols/openflow/api:onos-protocols-openflow-api',
    '//core/store/serializers:onos-core-serializers',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers',
    title = 'Default device drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS Default device drivers application.',
    included_bundles = [
        ':onos-drivers-default',
        '//lib:openflowj',
        '//protocols/openflow/api:onos-protocols-openflow-api',
    ]
)
