COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//apps/p4-tutorial/pipeconf:onos-apps-p4-tutorial-pipeconf',
]

osgi_jar (
    deps = COMPILE_DEPS,
)

BUNDLES = [
    '//apps/p4-tutorial/mytunnel:onos-apps-p4-tutorial-mytunnel',
]

onos_app (
    app_name = 'org.onosproject.p4tutorial.mytunnel',
    title = 'MyTunnel Demo App',
    category = 'Traffic Engineering',
    url = 'http://onosproject.org',
    description = 'Provides forwarding between each pair of hosts via MyTunnel protocol',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.p4tutorial.pipeconf',
    ]
)
