COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:KRYO',
    '//lib:JACKSON',
    '//lib:jsch',
    '//lib:org.apache.karaf.shell.console',
    '//lib:jackson-core',
    '//lib:jackson-annotations',
    '//lib:jackson-databind',
    '//cli:onos-cli',
    '//core/store/serializers:onos-core-serializers',
    '//apps/workflow/api:onos-apps-workflow-api',
]

osgi_jar(
    deps = COMPILE_DEPS,
)
