COMPILE_DEPS = CORE_DEPS + JACKSON + [
    "//incubator/api:onos-incubator-api",
    "//protocols/tl1/api:onos-protocols-tl1-api",
]

osgi_jar_with_tests(
    test_deps = TEST_ADAPTERS,
    deps = COMPILE_DEPS,
)
