COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//incubator/api:onos-incubator-api',
    '//protocols/snmp/api:onos-protocols-snmp-api',
    '//protocols/snmp/ctl:onos-protocols-snmp-ctl',
    '//providers/snmp/device:onos-providers-snmp-device',
    '//lib:org.apache.servicemix.bundles.snmp4j',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
