BUNDLES = [
    '//apps/cfm/api:onos-apps-cfm-api',
    '//apps/cfm/app:onos-apps-cfm-app',
    '//apps/cfm/nbi:onos-apps-cfm-nbi',
]

onos_app (
    title = 'Layer 2 Monitoring CFM Application',
    category = 'Monitoring',
    url = 'http://onosproject.org',
    description = 'Layer 2 Monitoring Connectivity Fault Management App',
    included_bundles = BUNDLES,
)
