BUNDLES = [
    "//apps/cfm/api:onos-apps-cfm-api",
    "//apps/cfm/app:onos-apps-cfm-app",
    "//apps/cfm/nbi:onos-apps-cfm-nbi",
]

onos_app(
    category = "Monitoring",
    description = "Layer 2 Monitoring Connectivity Fault Management App",
    included_bundles = BUNDLES,
    title = "Layer 2 Monitoring CFM Application",
    url = "http://onosproject.org",
)
