osgi_jar_with_tests(
    deps = CORE_DEPS,
)

onos_app(
    category = "Traffic Engineering",
    description = "Multicast forwarding application.",
    title = "Multicast Forwarding",
    url = "http://onosproject.org",
)
