BUNDLES = [
    "//apps/evpn-route-service/api:onos-apps-evpn-route-service-api",
    "//apps/evpn-route-service/app:onos-apps-evpn-route-service-app",
]

onos_app(
    category = "Traffic Engineering",
    included_bundles = BUNDLES,
    title = "EVPN Routing",
    url = "http://onosproject.org",
)
