COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//incubator/api:onos-incubator-api',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli'
]

osgi_jar (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'IPv6 RA Generator',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'Application for generating IPv6 RAs',
)
