COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//incubator/api:onos-incubator-api',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli'
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
    title = 'IPv6 RA Generator',
    category = 'Traffic Engineering',
    url = 'http://onosproject.org',
    description = 'Application for generating IPv6 RAs',
)
