COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//drivers/utilities:onos-drivers-utilities',
  '//protocols/netconf/api:onos-protocols-netconf-api',
]

BUNDLES = [
  ':onos-drivers-juniper',
  '//drivers/utilities:onos-drivers-utilities',
]

osgi_jar_with_tests (
  deps = COMPILE_DEPS,
  resources_root = 'src/main/resources',
  resources = glob(['src/main/resources/**']),
)

onos_app (
  app_name = 'org.onosproject.drivers.juniper',
  title = 'Juniper Drivers',
  category = 'Drivers',
  url = 'http://onosproject.org',
  description = 'Adds support for Juniper devices.',
  included_bundles = BUNDLES,
  required_apps = [ 'org.onosproject.netconf' ],
)