
filegroup(
    name = "onos-admin",
    srcs = [
        "bin/onos-create-app",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "onos-test",
    srcs = [
        "bash_profile",
        "bin/onos-create-app",
    ],
    visibility = ["//visibility:public"],
)