COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:kafka-clients',
    '//lib:jersey-client',
    '//lib:javax.ws.rs-api',
    '//lib:influxdb-java',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//core/common:onos-core-common-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
