PROTOBUF_VER = '3.2.0'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/p4runtime/proto:onos-protocols-p4runtime-proto',
    '//lib:protobuf-java-' + PROTOBUF_VER,
]

TEST_DEPS = [
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS + TEST_DEPS,
)
