PROTOBUF_VER = '3_2_0'

COMPILE_DEPS = CORE_DEPS + [
    #'//protocols/p4runtime/proto:onos-protocols-p4runtime-proto',
    #'@grpc_protobuf_' + PROTOBUF_VER + "//jar",
]

#osgi_jar_with_tests (
#    deps = COMPILE_DEPS,
#)
