BUNDLES = [
    "//protocols/bgp/bgpio:onos-protocols-bgp-bgpio",
    "//protocols/bgp/api:onos-protocols-bgp-api",
    "//protocols/bgp/ctl:onos-protocols-bgp-ctl",
    "//protocols/pcep/pcepio:onos-protocols-pcep-pcepio",
    "//apps/pcep-api:onos-apps-pcep-api",
    "//protocols/pcep/server/api:onos-protocols-pcep-server-api",
    "//providers/bgp/topology:onos-providers-bgp-topology",
    "//providers/bgp/cfg:onos-providers-bgp-cfg",
    "//protocols/pcep/server/ctl:onos-protocols-pcep-server-ctl",
    "//providers/pcep/topology:onos-providers-pcep-topology",
    "//providers/pcep/tunnel:onos-providers-pcep-tunnel",
    "//providers/bgpcep/flow:onos-providers-bgpcep-flow",
    "//apps/pce/app:onos-apps-pce-app",
    "//apps/pce/pceweb:onos-apps-pce-pceweb",
    "//apps/pce/bandwidthmgmt:onos-apps-pce-bandwidthmgmt",
]

onos_app(
    category = "Provider",
    description = "BGPCEP providers.",
    included_bundles = BUNDLES,
    title = "BGPCEP Provider",
    url = "http://onosproject.org",
)
