BUNDLES = [
    '//apps/openstacktroubleshoot/api:onos-apps-openstacktroubleshoot-api',
    '//apps/openstacktroubleshoot/app:onos-apps-openstacktroubleshoot-app',
]

onos_app (
    title = 'OpenStack Troubleshoot',
    category = 'Integration',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
    description = 'SONA Openstack Troubleshoot Application.',
    required_apps = [ 'org.onosproject.openstacknetworking' ]
)