BUNDLES = [
    "//apps/openstacktroubleshoot/api:onos-apps-openstacktroubleshoot-api",
    "//apps/openstacktroubleshoot/app:onos-apps-openstacktroubleshoot-app",
]

onos_app(
    category = "Integration",
    description = "SONA Openstack Troubleshoot Application.",
    included_bundles = BUNDLES,
    required_apps = ["org.onosproject.openstacknetworking"],
    title = "OpenStack Troubleshoot",
    url = "http://onosproject.org",
)
