osgi_jar_with_tests(
    deps = CORE_DEPS,
)

onos_app(
    category = "Utility",
    description = "ONOS Cluster IP alias application.",
    title = "Cluster IP Alias",
    url = "http://onosproject.org",
)
