COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:jersey-client',
    '//lib:jersey-server',
    '//lib:javax.ws.rs-api',
    '//lib:easymock',
    '//utils/rest:onlab-rest',
    '//apps/restconf/api:onos-apps-restconf-api',
    '//lib:onos-yang-model',
    '//lib:onos-yang-compiler-api',
    '//lib:onos-yang-runtime',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
