COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/lisp/api:onos-protocols-lisp-api',
    '//protocols/lisp/msg:onos-protocols-lisp-msg',
    '//lib:netty-buffer',
    '//lib:netty-codec',
    '//lib:netty-transport'
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//utils/osgi:onlab-osgi-tests',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

