BUNDLES = [
    '//protocols/restconf/server/rpp:onos-protocols-restconf-server-rpp',
]

onos_app (
  app_name = 'org.onosproject.protocols.restconfserver',
  title = 'RESTCONF Server Module',
  category = 'Utility',
  url = 'http://onosproject.org',
  included_bundles = BUNDLES,
)
