BUNDLES = [
    "//protocols/restconf/server/rpp:onos-protocols-restconf-server-rpp",
    "//apps/restconf/api:onos-apps-restconf-api",
]

onos_app(
    app_name = "org.onosproject.protocols.restconfserver",
    category = "Utility",
    included_bundles = BUNDLES,
    title = "RESTCONF Server Module",
    url = "http://onosproject.org",
)
