BUNDLES = [
    "//apps/openstackvtap/api:onos-apps-openstackvtap-api",
    "//apps/openstackvtap/app:onos-apps-openstackvtap-app",
]

onos_app(
    app_name = "org.onosproject.openstackvtap",
    category = "Integration",
    description = "Openstack Vtap Application.",
    included_bundles = BUNDLES,
    required_apps = [
        "org.onosproject.openstacknetworking",
    ],
    title = "Openstack Vtap Application",
    url = "https://wiki.onosproject.org/display/ONOS/SONA%3A+DC+Network+Virtualization",
)
