BUNDLES = [
    "//apps/openstackvtap/api:onos-apps-openstackvtap-api",
    "//apps/openstackvtap/app:onos-apps-openstackvtap-app",
]

onos_app(
    category = "Integration",
    description = "SONA Openstack vTap Application.",
    included_bundles = BUNDLES,
    required_apps = [
        "org.onosproject.openstacknetworking",
    ],
    title = "OpenStack vTap Application",
    url = "https://wiki.onosproject.org/display/ONOS/SONA%3A+DC+Network+Virtualization",
)
