COMPILE_DEPS = [
   '//lib:CORE_DEPS',
   '//lib:KRYO',
   '//core/api:onos-api',
   '//lib:org.apache.karaf.shell.console',
   '//utils/rest:onlab-rest',
   '//lib:JACKSON',
   '//lib:javax.ws.rs-api',
   '//lib:jersey-server',
   '//apps/t3/app:onos-apps-t3-app',
]
osgi_jar (
   deps = COMPILE_DEPS,
   web_context = '/onos/v1/t3',
   api_title = 'T3 REST API',
   api_version = '1.0',
   api_description = 'REST API for T3',
   api_package = 'org.onosproject.t3.rest',
)
