COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:METRICS',
    '//lib:org.apache.karaf.shell.console',
    '//lib:javax.ws.rs-api',
    '//utils/rest:onlab-rest',
    '//cli:onos-cli',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Topology &amp; Intent Metrics',
    category = 'Monitoring',
    url = 'http://onosproject.org',
    description = 'Monitoring of various metrics related to topology mutation and intent programming.',
)
