BUNDLES = [
    '//apps/route-service/api:onos-apps-route-service-api',
    '//apps/route-service/app:onos-apps-route-service-app',
]

onos_app (
    title = 'Route Service Server App',
    category = 'Utility',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
)
