BUNDLES = [
    "//apps/route-service/api:onos-apps-route-service-api",
    "//apps/route-service/app:onos-apps-route-service-app",
]

onos_app(
    category = "Utility",
    included_bundles = BUNDLES,
    title = "Route Service Server",
    url = "http://onosproject.org",
)
