COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/api:onos-incubator-api',
    '//apps/routing-api:onos-apps-routing-api',
    '//apps/route-service/api:onos-apps-route-service-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//incubator/api:onos-incubator-api-tests',
    '//apps/routing-api:onos-apps-routing-api-tests',
    '//apps/route-service/api:onos-apps-route-service-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

BUNDLES = [
    '//apps/routing/fibinstaller:onos-apps-routing-fibinstaller',
    '//apps/routing-api:onos-apps-routing-api',
]

onos_app (
    app_name = 'org.onosproject.fibinstaller',
    title = 'FIB Installer',
    category = 'Traffic Engineering',
    url = 'http://onosproject.org',
    description = 'Installs routing rules into switches',
    included_bundles = BUNDLES,
    required_apps = [ 'org.onosproject.route-service' ],
)
