COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//lib:commons-jxpath',
    '//apps/odtn/api:onos-apps-odtn-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//lib:slf4j-jdk14',
]

BUNDLES = [
    ':onos-drivers-odtn-driver',
#     '//lib:commons-jxpath',
#     '//lib:commons-beanutils', # jxpath dependency
#     '//lib:jdom',  # jxpath dependency
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.odtn-driver',
    title = 'ODTN Driver',
    category = 'Drivers',
    url = 'https://wiki.onosproject.org/display/ODTN/ODTN',
    description = 'Drivers related to ODTN',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.netconf',
        'org.onosproject.odtn-api',
    ],
)
