COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/api:onos-incubator-api',
    '//apps/routing-api:onos-apps-routing-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//incubator/api:onos-incubator-api-tests',
    '//apps/routing-api:onos-apps-routing-api-tests',
    '//utils/osgi:onlab-osgi-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

BUNDLES = [
    '//apps/routing/common:onos-apps-routing-common',
    '//apps/routing/cpr:onos-apps-routing-cpr',
    '//apps/routing-api:onos-apps-routing-api',
]

onos_app (
    app_name = 'org.onosproject.cpr',
    title = 'Control plane redirect',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'Redirects routing control traffic to a control plane',
    included_bundles = BUNDLES,
)
