BUNDLES = [
    '//protocols/xmpp/core/api:onos-protocols-xmpp-core-api',
    '//protocols/xmpp/pubsub/api:onos-protocols-xmpp-pubsub-api',
    '//protocols/xmpp/pubsub/ctl:onos-protocols-xmpp-pubsub-ctl',
    '//lib:tinder-xmpp',
    '//lib:concurrent-hashmap',
    '//lib:gnu-idn',
]

onos_app(
    app_name = 'org.onosproject.protocols.xmpp.pubsub',
    title = 'XMPP Publish/Subscribe protocol extension subsystem',
    category = 'Protocol',
    url = 'http://onosproject.org',
    description = 'XMPP Publish/Subscribe protocol extension subsystem',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.protocols.xmpp',
    ]
)