BUNDLES = [
    '//providers/lisp/device:onos-providers-lisp-device',
    '//providers/lisp/mapping:onos-providers-lisp-mapping',
    '//providers/lisp/message:onos-providers-lisp-message',
    '//protocols/lisp/api:onos-protocols-lisp-api',
    '//protocols/lisp/ctl:onos-protocols-lisp-ctl',
    '//protocols/lisp/msg:onos-protocols-lisp-msg',
    '//apps/mappingmanagement/api:onos-apps-mappingmanagement-api',
]

onos_app (
    app_name = 'org.onosproject.lisp',
    title = 'LISP Provider',
    category = 'Provider',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
    description = 'LISP protocol southbound providers.',
)
