COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/api:onos-incubator-api',
    '//utils/rest:onlab-rest',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/rest/api:onos-protocols-rest-api',
    '//apps/optical-model:onos-apps-optical-model',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]

BUNDLES = [
    ':onos-drivers-ciena',
    '//drivers/utilities:onos-drivers-utilities',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.ciena',
    title = 'Ciena Device Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS Ciena Device Drivers application.',
    included_bundles = BUNDLES,
    required_apps = [ 'org.onosproject.restsb', 'org.onosproject.optical-model' ],
)
