BUNDLES = [
    "//apps/tunnel/api:onos-apps-tunnel-api",
    "//apps/tunnel/app:onos-apps-tunnel-app",
]

onos_app(
    app_name = "org.onosproject.tunnel",
    category = "Traffic Engineering",
    description = "Tunnel Subsystem extension",
    included_bundles = BUNDLES,
    title = "Tunnel Subsystem",
    url = "http://onosproject.org",
)
