COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/pcep/pcepio:onos-protocols-pcep-pcepio',
    '//protocols/pcep/api:onos-protocols-pcep-api',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

