BUNDLES = [
  '//apps/yms/api:onos-apps-yms-api',
  '//apps/yms/app:onos-apps-yms-app',
  '//lib:onos-yang-datamodel',
  '//lib:onos-yang-utils-generator',
  '//lib:org.apache.servicemix.bundles.dom4j',
]

onos_app(
  title = 'YANG Management System App',
  category = 'Utility',
  url = 'http://onosproject.org',
  included_bundles = BUNDLES,
)
