BUNDLES = [
    '//providers/p4runtime/packet:onos-providers-p4runtime-packet',
]

onos_app (
    app_name = 'org.onosproject.p4runtime',
    title = 'P4Runtime Provider',
    category = 'Provider',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
    description = 'P4Runtime southbound providers.',
    required_apps = [
        'org.onosproject.protocols.p4runtime',
    ]
)


