BUNDLES = [
    "//providers/p4runtime/packet:onos-providers-p4runtime-packet",
]

onos_app(
    app_name = "org.onosproject.p4runtime",
    category = "Provider",
    description = "P4Runtime southbound providers.",
    included_bundles = BUNDLES,
    required_apps = [
        "org.onosproject.protocols.p4runtime",
    ],
    title = "P4Runtime Provider",
    url = "http://onosproject.org",
)
