COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//models/ietf:onos-models-ietf',
]

APPS = [
    'org.onosproject.models.ietf',
]

yang_model(
  app_name = 'org.onosproject.models.openconfig-infinera',
  title = 'OpenConfig Infinera XT3300 YANG Models',
  custom_registrator = False,
  deps = COMPILE_DEPS,
  required_apps = APPS,
)
