COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:openflowj',
    '//lib:netty-transport',
]

TEST_DEPS = [
    '//lib:TEST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
