COMPILE_DEPS = [
    '//incubator/api:onos-incubator-api',
    '//utils/rest:onlab-rest',
    '//lib:CORE_DEPS',
    '//lib:jersey-client',
    '//lib:jersey-security',
    '//lib:jersey-common',
    '//lib:httpclient-osgi',
    '//lib:httpcore-osgi',
    '//lib:javax.ws.rs-api',
    '//lib:hk2-api',
    '//lib:aopalliance-repackaged',
    '//lib:javax.inject',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
