COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//apps/yms/api:onos-apps-yms-api',
    '//protocols/restconf/server/utils:onos-protocols-restconf-server-utils',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//utils/osgi:onlab-osgi-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
