COMPILE_DEPS = CORE_DEPS + [
    "//protocols/ovsdb/api:onos-protocols-ovsdb-api",
    "//protocols/ovsdb/rfc:onos-protocols-ovsdb-rfc",
    "//apps/tunnel/api:onos-apps-tunnel-api",
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
