COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/ovsdb/api:onos-protocols-ovsdb-api',
    '//protocols/ovsdb/rfc:onos-protocols-ovsdb-rfc',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

