COMPILE_DEPS = CORE_DEPS + [
    "//incubator/api:onos-incubator-api",
]

osgi_jar(
    deps = COMPILE_DEPS,
)

onos_app(
    category = "Traffic Engineering",
    description = "Proxy ARP/NDP application.",
    title = "Proxy ARP/NDP",
    url = "http://onosproject.org",
)
