BUNDLES = [
    '//incubator/api:onos-incubator-api',
    '//apps/yms/api:onos-apps-yms-api',
    '//apps/tetopology/api:onos-apps-tetopology-api',
    '//apps/tetunnel/api:onos-apps-tetunnel-api',
    '//apps/tenbi/utils:onos-apps-tenbi-utils',
    '//apps/tenbi/tunnel:onos-apps-tenbi-tunnel',
    '//apps/tenbi/topology:onos-apps-tenbi-topology',
]

onos_app (
    app_name = 'org.onosproject.tenbi',
    title = 'TE NBI',
    category = 'ACTN APP',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
    description = 'The northbound interface of TE topology and TE tunnel.',
    required_features = [ 'onos-apps-tenbi-yangmodel' ],
    required_apps = [ 'org.onosproject.tetopology',
                      'org.onosproject.tetunnel',
                      'org.onosproject.yms' ],
)

