COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/api:onos-incubator-api',
    '//apps/routing-api:onos-apps-routing-api',
]

BUNDLES = [
    '//apps/routing-api:onos-apps-routing-api',
    '//apps/sdnip:onos-apps-sdnip',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//incubator/api:onos-incubator-api-tests',
    '//apps/routing-api:onos-apps-routing-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
  title = 'SDN-IP App',
  category = 'Utility',
  url = 'http://onosproject.org',
  included_bundles = BUNDLES,
  description = 'SDN-IP peering application',
)
