COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:jersey-client',
    '//lib:jersey-server',
    '//lib:javax.ws.rs-api',
    '//utils/rest:onlab-rest',
    '//apps/restconf/api:onos-apps-restconf-api',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    web_context = '/onos/restconf',
)
