BUNDLES = [
    "//apps/virtual/api:onos-apps-virtual-api",
    "//apps/virtual/app:onos-apps-virtual-app",
]

onos_app(
    app_name = "org.onosproject.virtual",
    category = "Traffic Engineering",
    description = "Virtual Network Subsystem extension",
    included_bundles = BUNDLES,
    required_apps = [
        "org.onosproject.tunnel",
    ],
    title = "Virtual Network Subsystem",
    url = "http://onosproject.org",
)
