BUNDLES = [
  '//apps/network-troubleshoot/api:onos-apps-network-troubleshoot-api',
  '//apps/network-troubleshoot/cli:onos-apps-network-troubleshoot-cli',
  '//apps/network-troubleshoot/core:onos-apps-network-troubleshoot-core',
]

onos_app (
  title = 'Network Troubleshooter',
  description = 'Provides various network troubleshooting utilities.',
  category = 'Utility',
  url = 'https://wiki.onosproject.org/display/ONOS/Network+TroubleShooting+Module',
  included_bundles = BUNDLES,
)
