BUNDLES = [
    "//apps/network-troubleshoot/api:onos-apps-network-troubleshoot-api",
    "//apps/network-troubleshoot/cli:onos-apps-network-troubleshoot-cli",
    "//apps/network-troubleshoot/core:onos-apps-network-troubleshoot-core",
]

onos_app(
    category = "Utility",
    description = "Provides various network troubleshooting utilities.",
    included_bundles = BUNDLES,
    title = "Network Troubleshooter",
    url = "https://wiki.onosproject.org/display/ONOS/Network+TroubleShooting+Module",
)
