#!/bin/bash
# -----------------------------------------------------------------------------
# Exports the ONOS Tutorial VM into an OVA file for publishing.
# -----------------------------------------------------------------------------

export VER=1.14.0
export OVA=/tmp/onos-tutorial-$VER.ova
rm -f $OVA
vboxmanage export "ONOS Tutorial" --output $OVA --manifest \
	--vsys 0 --product "ONOS" --vendor "Open Networking Foundation" --version "$VER" \
        --description "ONOS Basic Tutorial VM; 3 node cluster using docker; mininet topologies"
wc -c $OVA