#!/bin/bash
# -----------------------------------------------------------------------------
# Publishes the ONOS Tutorial OVA file.
# -----------------------------------------------------------------------------
export VER=1.14.0
export OVA=/tmp/onos-tutorial-$VER.ova
uploadToS3.py $OVA --secret $AWS_SECRET_ACCESS_KEY --key $AWS_ACCESS_KEY_ID --bucket onos --dest vm/
