COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//core/api:onos-api',
    '//lib:tinder-xmpp',
    '//lib:io_netty_netty_transport',
    '//lib:io_netty_netty_common',
    '//lib:org.apache.servicemix.bundles.dom4j',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)