COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//core/store/serializers:onos-core-serializers',
]

TEST_DEPS = [
    '//lib:TEST',
]

osgi_jar_with_tests (
    name = 'onos-security',
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    visibility = ['PUBLIC'],
)
