BUNDLES = [
    "//apps/dpistats/api:onos-apps-dpistats-api",
    "//apps/dpistats/app:onos-apps-dpistats-app",
]

onos_app(
    app_name = "org.onosproject.dpistats",
    category = "Traffic Engineering",
    description = "dpistats Network Subsystem extension",
    included_bundles = BUNDLES,
    title = "dpistats Network Subsystem",
    url = "http://onosproject.org",
)
