APPS = [
    'org.onosproject.yang',
]

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:KRYO',
    '//lib:org.apache.karaf.shell.console',
    '//lib:onos-yang-model',
    '//core/store/serializers:onos-core-serializers',
    '//cli:onos-cli',
    '//lib:commons-text',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Dynamic Configuration',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'Provides means to track and distribute service and device configuration data ' +
        'throughout the ONOS cluster. It works with the YANG runtime to ensure that the tracked ' +
        'data adheres to the registered YANG models. Applications can traverse and access this ' +
        'data which is organized in a logically unified tree.<p/>(Under development)',
    required_apps = APPS,
)
