BUNDLES = [
    "//apps/onos-topo/api:onos-apps-onos-topo-api",
    "//apps/onos-topo/app:onos-apps-onos-topo-app",
]

onos_app(
    category = "Integrations",
    included_bundles = BUNDLES,
    required_apps = [
        "org.onosproject.protocols.grpc",
    ],
    title = "µONOS Integration",
    url = "http://onosproject.org",
)
