COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
    '//lib:javax.ws.rs-api',
    '//utils/rest:onlab-rest',
    '//protocols/ovsdb/api:onos-protocols-ovsdb-api',
    '//protocols/ovsdb/rfc:onos-protocols-ovsdb-rfc',
    '//core/store/serializers:onos-core-serializers',
    '//apps/openstacknode/api:onos-apps-openstacknode-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//core/common:onos-core-common-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    web_context = '/onos/openstacknode',
    api_title = 'OpenStack Node App API',
    api_version = '1.0',
    api_description = 'REST API for OpenStack Node App',
    api_package = 'org.onosproject.openstacknode.web',
)

