COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//lib:JACKSON',
    '//lib:io_netty_netty_buffer',
    '//lib:io_netty_netty_codec',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

