COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:concurrent-trees',
    '//incubator/api:onos-incubator-api',
    '//apps/routing-api:onos-apps-routing-api',
    '//apps/intentsync:onos-apps-intentsync',
    '//apps/route-service/api:onos-apps-route-service-api',
]

osgi_jar (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'SDN-IP Reactive Routing',
    category = 'Traffic Engineering',
    url = 'http://onosproject.org',
    description = 'SDN-IP reactive routing application.',
    required_apps = [ 'org.onosproject.intentsynchronizer', 'org.onosproject.sdnip', 'org.onosproject.route-service'],
)
