COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//drivers/default:onos-drivers-default',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//apps/optical-model:onos-apps-optical-model',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]

BUNDLES = [
    ':onos-drivers-oplink',
    '//drivers/utilities:onos-drivers-utilities',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app(
    app_name = 'org.onosproject.drivers.oplink',
    title = 'Oplink Device Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS Oplink Device Drivers application.',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.netconf', 'org.onosproject.optical-model'
    ],
)