SRC_DEPS = [
    '//lib:junit',
    '//lib:hamcrest-all',
    '//lib:guava',
]

TEST_DEPS = [
    '//lib:guava-testlib',
]

osgi_jar_with_tests(
    name = 'onlab-junit',
    srcs = glob([SRC + '/*.java']),
    deps = SRC_DEPS,
    test_deps = TEST_DEPS,
    visibility = ['PUBLIC'],
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
    package_name_root = 'org.onlab',
)
