COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//core/store/serializers:onos-core-serializers',
    '//utils/rest:onlab-rest',
    '//lib:javax.ws.rs-api',
]

TEST_DEPS = [
    '//lib:TEST_REST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    web_context = '/onos/powermanagement',
    api_title = 'Power Management API',
    api_version = '1.0',
    api_description = 'REST API for Power Management',
    api_package = 'org.onosproject.powermanagement',
)

onos_app (
    title = 'Power Management',
    category = 'Monitoring',
    url = 'http://onosproject.org',
    description = 'This application provides northbound interfaces for monitoring and ' +
        'configuring power.',
)
