COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.servicemix.bundles.snmp4j',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/snmp/api:onos-protocols-snmp-api',
    '//apps/optical-model:onos-apps-optical-model',
    '//incubator/api:onos-incubator-api',
]

APPS = [
    'org.onosproject.snmp',
    'org.onosproject.optical-model',
    'org.onosproject.faultmanagement',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app(
    app_name = 'org.onosproject.drivers.polatis.snmp',
    title = 'Polatis SNMP Device Drivers',
    category = 'Drivers',
    url = 'http://www.polatis.com',
    description = 'ONOS Polatis SNMP Device Drivers application.',
    required_apps = APPS
)
