COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:KRYO',
    '//cli:onos-cli',
    '//core/store/serializers:onos-core-serializers',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
    app_name = 'org.onosproject.portloadbalancer',
    category = 'Utilities',
    description = 'Port Load Balance Service',
    title = 'Port Load Balance Service',
    url = 'http://onosproject.org',
)
