COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.karaf.shell.console',
    '//lib:javax.ws.rs-api',
    '//lib:rrd4j',
    '//apps/cpman/api:onos-apps-cpman-api',
    '//utils/rest:onlab-rest',
    '//cli:onos-cli',
    '//core/store/serializers:onos-core-serializers',
]

TEST_DEPS = [
    '//lib:TEST_REST',
    '//web/api:onos-rest-tests',
]

BUNDLES = [
    '//apps/cpman/api:onos-apps-cpman-api',
    ':onos-apps-cpman-app',
]

EXCLUDED_BUNDLES = [
    '//lib:rrd4j',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    web_context = '/onos/cpman',
)

onos_app (
    app_name = 'org.onosproject.cpman',
    title = 'Control Plane Manager application',
    category = 'Monitoring',
    url = 'http://onosproject.org',
    description = 'Control Plane Management application for monitoring the health of the ONOS cluster',
    included_bundles = BUNDLES,
    excluded_bundles = EXCLUDED_BUNDLES,
    required_apps = [ 'org.onosproject.openflow-message' ],
)
