COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//core/store/serializers:onos-core-serializers',
  '//lib:org.apache.karaf.shell.console',
  '//cli:onos-cli',
  '//apps/optical-model:onos-apps-optical-model',
]

TEST_DEPS = [
  '//lib:TEST_ADAPTERS',
  '//utils/osgi:onlab-osgi-tests',
]

osgi_jar_with_tests (
  deps = COMPILE_DEPS,
  test_deps = TEST_DEPS,
)

onos_app (
  title = 'Packet/Optical Use-Case App',
  category = 'Traffic Steering',
  url = 'http://onosproject.org',
  description = 'Packet/Optical use-case application.',
  required_apps = [ 'org.onosproject.optical-model' ],
)
