COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:ganymed-ssh2',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//cli:onos-cli',
    '//lib:org.apache.karaf.shell.console',
    '//lib:sshd-core',
    '//lib:bcpkix-jdk15on',
    '//lib:bcprov-jdk15on',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//utils/osgi:onlab-osgi-tests',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

