COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:ganymed-ssh2',
    '//protocols/netconf/api:onos-protocols-netconf-api'
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//utils/osgi:onlab-osgi-tests',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

