COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:javax.ws.rs-api',
    '//incubator/api:onos-incubator-api',
    '//utils/rest:onlab-rest',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/rest/api:onos-protocols-rest-api',
    '//apps/optical-model:onos-apps-optical-model',
    '//drivers/optical:onos-drivers-optical',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]

BUNDLES = [
    ':onos-drivers-ciena-waveserver',
    '//drivers/utilities:onos-drivers-utilities',
]

REQUIRED_APPS = [
    'org.onosproject.restsb',
    'org.onosproject.optical-model',
    'org.onosproject.drivers.optical',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.ciena.waveserver.rest',
    title = 'Ciena Waveserver Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'Adds support for Ciena Waveserver devices.',
    included_bundles = BUNDLES,
    required_apps = REQUIRED_APPS,
)
