COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:onos-yang-model',
    '//lib:onos-yang-runtime',
    '//apps/config:onos-apps-config',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//apps/netconfsb/client:onos-apps-netconfsb-client'


]

osgi_jar_with_tests (
  deps = COMPILE_DEPS,
)

BUNDLES = [
  '//apps/netconfsb/client:onos-apps-netconfsb-client',
  '//apps/netconfsb/storeadapter:onos-apps-netconfsb-storeadapter',
]

onos_app (
  app_name = 'org.onosproject.netconfsb',
  title = 'NETCONF Application Module',
  category = 'Utility',
  url = 'http://onosproject.org',
  description = """This application provides an interface for monitoring and modifying datastores
                   of NETCONF devices using Yang data. It uses the YangRuntime to serialize outbound
                   messages from Yang into NETCONF and deserialize received messages.""",
  included_bundles = BUNDLES,
)
