APPS = [
  'org.onosproject.yang',
]

BUNDLES = [
  '//apps/l3vpn/yangmodel:onos-apps-l3vpn-yangmodel',
  '//apps/l3vpn/netl3vpn:onos-apps-l3vpn-netl3vpn',
]

onos_app(
  app_name = 'org.onosproject.l3vpn',
  title = 'YANG L3VPN App',
  category = 'L3VPN APP',
  url = 'http://onosproject.org',
  included_bundles = BUNDLES,
  description = 'L3VPN YANG Application',
  required_apps = APPS,
)

