BUNDLES = [
    "//apps/packet-throttle/app:onos-apps-packet-throttle-app",
]

onos_app(
    app_name = "org.onosproject.packetthrottle",
    category = "Traffic Steering",
    description = "Packet throttle application to make ONOS drop packets crossing threshold",
    included_bundles = BUNDLES,
    title = "Packet Throttler",
    url = "http://onosproject.org",
)
