COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//incubator/api:onos-incubator-api',
  '//protocols/pcep/server/ctl:onos-protocols-pcep-server-ctl',
  '//protocols/pcep/server/api:onos-protocols-pcep-server-api',
  '//lib:org.apache.karaf.shell.console',
  '//cli:onos-cli',
]

osgi_jar_with_tests (
  deps = COMPILE_DEPS,
)
