COMPILE_DEPS = CORE_DEPS + CLI + [
    "//incubator/api:onos-incubator-api",
    "//protocols/pcep/server/ctl:onos-protocols-pcep-server-ctl",
    "//protocols/pcep/server/api:onos-protocols-pcep-server-api",
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
