COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:sigar',
    '//lib:org.apache.karaf.shell.console',
    '//apps/nodemetrics/api:onos-apps-nodemetrics-api',
    '//core/store/serializers:onos-core-serializers',
    '//cli:onos-cli',
    '//lib:KRYO',
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)