COMPILE_DEPS = CORE_DEPS + KRYO + [
    "//core/store/serializers:onos-core-serializers",
    "//apps/evpn-route-service/api:onos-apps-evpn-route-service-api",
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
