COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/ospf/api:onos-protocols-ospf-api',
    '//protocols/ospf/ctl:onos-protocols-ospf-ctl',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

