BUNDLES = [
    '//apps/dhcp/api:onos-apps-dhcp-api',
    '//apps/dhcp/app:onos-apps-dhcp-app',
]

onos_app(
  feature_coords = ONOS_GROUP_ID + ':onos-apps-dhcp:' + ONOS_VERSION,
  title = 'DHCP Server App',
  category = 'Utility',
  url = 'http://onosproject.org',
  included_bundles = BUNDLES,
)
