BUNDLES = [
    "//apps/dhcp/api:onos-apps-dhcp-api",
    "//apps/dhcp/app:onos-apps-dhcp-app",
]

onos_app(
    category = "Utility",
    included_bundles = BUNDLES,
    required_apps = ["org.onosproject.hostprovider"],
    title = "DHCP Server",
    url = "http://onosproject.org",
)
