COMPILE_DEPS = CORE_DEPS + [
    "@io_netty_netty//jar",
    "//apps/tunnel/api:onos-apps-tunnel-api",
    "//protocols/pcep/pcepio:onos-protocols-pcep-pcepio",
    "//apps/pcep-api:onos-apps-pcep-api",
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
