COMPILE_DEPS = CORE_DEPS + [
    "@io_netty_netty//jar",
    "//protocols/pcep/pcepio:onos-protocols-pcep-pcepio",
    "//apps/pcep-api:onos-apps-pcep-api",
    "//incubator/api:onos-incubator-api",
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
