COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//lib:JACKSON',
  '//core/store/serializers:onos-core-serializers',
  '//lib:javax.ws.rs-api',
  '//utils/rest:onlab-rest',
  '//lib:jersey-client',
  '//cli:onos-cli',
  '//lib:org.apache.karaf.shell.console',
  '//lib:sshd-core',
  '//apps/openstacknode/api:onos-apps-openstacknode-api',
  '//apps/openstacktelemetry/api:onos-apps-openstacktelemetry-api',
  '//apps/openstacknetworking/api:onos-apps-openstacknetworking-api',
  '//apps/openstacknetworking/app:onos-apps-openstacknetworking-app',
]

EXCLUDED_BUNDLES = [
  '//lib:sshd-core',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//core/common:onos-core-common-tests',
]

osgi_jar_with_tests (
  deps = COMPILE_DEPS,
  test_deps = TEST_DEPS,
)

onos_app (
  app_name = 'org.onosproject.openstacknetworkingui',
  title = 'Openstack Networking UI',
  category = 'GUI',
  url = 'http://onosproject.org',
  description = 'Openstack Networking UI Service',
  excluded_bundles = EXCLUDED_BUNDLES,
  required_apps = [
      'org.onosproject.openstacknetworking',
  ]
)
