COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//lib:JACKSON',
  '//core/store/serializers:onos-core-serializers',
  '//lib:javax.ws.rs-api',
  '//utils/rest:onlab-rest',
  '//lib:jersey-client',
  '//cli:onos-cli',
  '//lib:org.apache.karaf.shell.console',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
    '//core/common:onos-core-common-tests',
]

osgi_jar_with_tests (
  deps = COMPILE_DEPS,
  test_deps = TEST_DEPS,
  web_context = '/onos/openstacknetworkingui',
  api_title = 'OpenStack Networking UI REST API',
  api_version = '0.9',
  api_description = 'OpenStack Networking UI REST API',
  api_package = 'org.onosproject.openstacknetworkingui.web',
)

onos_app (
  app_name = 'org.onosproject.openstacknetworkingui',
  title = 'Openstack Networking UI',
  category = 'GUI',
  url = 'http://onosproject.org',
  description = 'Openstack Networking UI Service',
)
