COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:NETTY',
    '//protocols/ovsdb/api:onos-protocols-ovsdb-api',
    '//protocols/ovsdb/rfc:onos-protocols-ovsdb-rfc',
    '//apps/pcep-api:onos-apps-pcep-api',
    '//incubator/api:onos-incubator-api',
    '//protocols/pcep/pcepio:onos-protocols-pcep-pcepio',
    '//protocols/pcep/server/api:onos-protocols-pcep-server-api',
    '//protocols/pcep/server/ctl:onos-protocols-pcep-server-ctl',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//lib:netty',
    '//lib:netty-transport',
    '//protocols/pcep/server/api:onos-protocols-pcep-server-api-tests',
    '//apps/pcep-api:onos-apps-pcep-api-tests',
    '//incubator/api:onos-incubator-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
