COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/ovsdb/api:onos-ovsdb-api',
    '//protocols/ovsdb/rfc:onos-ovsdb-rfc',
    '//apps/pcep-api:onos-apps-pcep-api',
    '//incubator/api:onos-incubator-api',
    '//protocols/pcep/pcepio:onos-pcep-pcepio',
    '//protocols/pcep/api:onos-pcep-controller-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
