COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:JACKSON',
    '//lib:org.apache.karaf.shell.console',
    '//core/common:onos-core-common',
    '//cli:onos-cli',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'UI Auto-Layout',
    category = 'GUI',
    url = 'http://onosproject.org',
    description = 'Automatically lays out the network topology using roles assigned to each ' +
        'network element via the network configuration. Supports multiple layout variants.',
)
