SRC = 'src/main/java/org/onosproject/**/'

CURRENT_NAME = 'onos-drivers-lumentum'
CURRENT_TARGET = ':' + CURRENT_NAME

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.servicemix.bundles.snmp4j',
    '//drivers/utilities:onos-drivers-utilities',
]

java_library(
    name = CURRENT_NAME,
    srcs = glob([SRC + '/*.java']),
    deps = COMPILE_DEPS,
    visibility = ['PUBLIC'],
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)
