COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.servicemix.bundles.snmp4j',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/snmp/api:onos-protocols-snmp-api',
    '//protocols/tl1/api:onos-protocols-tl1-api',
    '//protocols/netconf/api:onos-protocols-netconf-api',
    '//incubator/api:onos-incubator-api',
    '//apps/optical-model:onos-apps-optical-model',
    '//drivers/optical:onos-drivers-optical',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]

BUNDLES = [
    ':onos-drivers-lumentum',
    '//drivers/utilities:onos-drivers-utilities',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.lumentum',
    title = 'Lumentum Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',

    description = 'ONOS Lumentum Device Drivers application.',
    included_bundles = BUNDLES,
    required_apps = [ 'org.onosproject.snmp', 'org.onosproject.faultmanagement', 'org.onosproject.optical-model',
     'org.onosproject.tl1', 'org.onosproject.netconf', 'org.onosproject.drivers.optical'],

)
