COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.servicemix.bundles.snmp4j',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/snmp/api:onos-protocols-snmp-api',
    '//incubator/api:onos-incubator-api',
    '//apps/optical-model:onos-apps-optical-model',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.lumentum',
    title = 'Lumentum Device Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS Lumentum Device Drivers application.',
    required_apps = [ 'org.onosproject.snmp', 'org.onosproject.faultmanagement', 'org.onosproject.optical-model' ],
)
