BUNDLES = [
    "//providers/tl1/device:onos-providers-tl1-device",
    "//protocols/tl1/api:onos-protocols-tl1-api",
    "//protocols/tl1/ctl:onos-protocols-tl1-ctl",
]

onos_app(
    app_name = "org.onosproject.tl1",
    category = "Provider",
    description = "Provides means for ONOS to discover and trigger the initial handshake procedure " +
                  "with TL1 enable devices from information given by network configuration.",
    included_bundles = BUNDLES,
    title = "TL1 Provider",
    url = "https://wiki.onosproject.org/display/ONOS/TL1",
)
