COMPILE_DEPS = [
    '//lib:CORE_DEPS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.netcfghostprovider',
    title = 'Network Config Host Provider',
    category = 'Provider',
    url = 'http://onosproject.org',
    description = 'Allows operator to prescribe information about known hosts and their locations ' +
        'using the network configuration subsystem. Such information takes precedence over ' +
        'information discovered through other host location providers.',
)

