osgi_jar_with_tests(
    deps = CORE_DEPS,
)

onos_app(
    app_name = "org.onosproject.netcfghostprovider",
    category = "Provider",
    description = "Allows operator to prescribe information about known hosts and their locations " +
                  "using the network configuration subsystem. Such information takes precedence over " +
                  "information discovered through other host location providers.",
    title = "Network Config Host Provider",
    url = "http://onosproject.org",
)
