COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:openflowj',
    '//protocols/openflow/api:onos-protocols-openflow-api',
    '//drivers/default:onos-drivers-default',
    '//apps/optical-model:onos-apps-optical-model',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.optical',
    title = 'Other optical Device Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS other optical Device Drivers application.',
    required_apps = [ 'org.onosproject.drivers', 'org.onosproject.optical-model' ],
)
