COMPILE_DEPS = CORE_DEPS + [
    "//incubator/api:onos-incubator-api",
    "//utils/rest:onlab-rest",
    "//protocols/rest/api:onos-protocols-rest-api",
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
