COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//lib:org.apache.karaf.shell.console',
  '//cli:onos-cli',
  '//incubator/api:onos-incubator-api',
  '//core/store/serializers:onos-core-serializers',
  '//apps/gluon:onos-apps-gluon',
  '//apps/vtn/vtnrsc:onos-apps-vtn-vtnrsc',
]

TEST_DEPS = [
  '//lib:TEST_ADAPTERS',
  '//lib:TEST',
]

osgi_jar_with_tests(
  deps = COMPILE_DEPS,
  test_deps = TEST_DEPS,
)

onos_app(
  title = 'Evpn-openflow App',
  category = 'Traffic Steering',
  url = 'http://onosproject.org',
  description = 'Ethernet VPN (EVPN) introduces a new model for Ethernet services delivery.' +
  'It enables integrated Layer 2 service over Ethernet with multihoming.',
)
