GRPC_VER = '1.3.1'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:KRYO',
    '//protocols/p4runtime/api:onos-protocols-p4runtime-api',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//core/store/serializers:onos-core-serializers',
]

BUNDLES = [
    ':onos-drivers-p4runtime',
]

osgi_jar (
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.drivers.p4runtime',
    title = 'P4Runtime Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'Adds support for devices using P4 Runtime protocol.',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.generaldeviceprovider',
        'org.onosproject.protocols.p4runtime',
        'org.onosproject.p4runtime',
        'org.onosproject.drivers',
    ],
)
