COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//core/api:onos-api',
    '//lib:tinder-xmpp',
    '//lib:concurrent-hashmap',
    '//lib:gnu-idn',
    '//protocols/xmpp/pubsub/api:onos-protocols-xmpp-pubsub-api',
    '//protocols/xmpp/core/api:onos-protocols-xmpp-core-api',
]

TEST_DEPS = [
    '//lib:TEST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)