SRC = 'src/main/java/org/onosproject/**/'

CURRENT_NAME = 'onos-snmp-api'
CURRENT_TARGET = ':' + CURRENT_NAME

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/api:onos-incubator-api',
    '//lib:org.apache.servicemix.bundles.snmp4j',
    '//lib:snmp-core',
    '//lib:bti7000',
    '//lib:mibs-net-snmp',
    '//lib:mibs-rfc',
]

osgi_jar(
    name = CURRENT_NAME,
    srcs = glob([SRC + '/*.java']),
    deps = COMPILE_DEPS,
    visibility = ['PUBLIC'],
)
