BUNDLES = [
    "//apps/workflow/api:onos-apps-workflow-api",
    "//apps/workflow/app:onos-apps-workflow-app",
]

onos_app(
    category = "Utility",
    description = "Workflow application",
    included_bundles = BUNDLES,
    title = "Workflow",
    url = "http://onosproject.org",
)
