COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:jackson-core',
    '//lib:jackson-annotations',
    '//lib:jackson-databind',
    '//core/store/serializers:onos-core-serializers',
    '//apps/workflow/api:onos-apps-workflow-api',
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
