COMPILE_DEPS = CORE_DEPS + KRYO + JACKSON + [
    "//core/store/serializers:onos-core-serializers",
    "//apps/workflow/api:onos-apps-workflow-api",
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
