COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
    '//core/store/serializers:onos-core-serializers',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
  title = 'Scalable GW App',
  category = 'Utility',
  url = 'http://onosproject.org',
  description = 'Scalable gateway service',
)
