COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:org.apache.karaf.shell.console',
    '//lib:concurrent-trees',
    '//cli:onos-cli',
    '//incubator/api:onos-incubator-api',
    '//apps/routing-api:onos-apps-routing-api',
    '//core/common:onos-core-common',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//incubator/api:onos-incubator-api-tests',
    '//apps/routing-api:onos-apps-routing-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
