COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//apps/yms/api:onos-apps-yms-api',
  '//lib:onos-yang-datamodel',
  '//lib:onos-yang-utils-generator',
  '//lib:org.apache.servicemix.bundles.dom4j',
]

osgi_jar_with_tests(
  name = 'onos-apps-yms-app',
  deps = COMPILE_DEPS,
  #private_packages = 'org.onosproject.yangutils.datamodel.*,org.onosproject.yangutils.translator.*,org.onosproject.yangutils.linker.*,org.onosproject.yangutils.utils.*',
)
