GRPC_VER = '1.3.0'

COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//incubator/grpc-dependencies:grpc-core-repkg-' + GRPC_VER,
    '//lib:grpc-stub-' + GRPC_VER,
]

osgi_jar (
    deps = COMPILE_DEPS,
)
