COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:grpc-core-1.3.0',
    '//lib:grpc-protobuf-1.3.0',
    '//lib:grpc-stub-1.3.0',
    '//lib:grpc-netty-1.3.0',
    '//lib:grpc-auth-1.3.0',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
