BUNDLES = [
  '//apps/tetopology/api:onos-apps-tetopology-api',
]

onos_app (
    title = 'TE Topology Core App',
    category = 'ACTN',
    url = 'http://onosproject.org',
    description = 'Application to create and manage hierarchical TE topologies.',
    included_bundles = BUNDLES,
)
