COMPILE_DEPS = [
    '//lib:CORE_DEPS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'TE Topology Core App',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'Application to create and manage hierarchical TE topologies.',
)
