BUNDLES = [
    "//apps/tetopology/api:onos-apps-tetopology-api",
    "//apps/tetopology/app:onos-apps-tetopology-app",
]

onos_app(
    app_name = "org.onosproject.tetopology",
    category = "Traffic Engineering",
    description = "Application to create and manage hierarchical TE topologies.",
    included_bundles = BUNDLES,
    title = "TE Topology Core",
    url = "http://onosproject.org",
)
