COMPILE_DEPS = [
    '//lib:COMPILE',
    '//utils/osgi:onlab-osgi',
    '//utils/misc:onlab-misc',
    '//lib:javax.ws.rs-api',
    '//lib:jersey-server',
]

osgi_jar_with_tests (
    name = 'onlab-rest',
    deps = COMPILE_DEPS,
    package_name_root = 'org.onlab',
)
