COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:onos-yang-model',
    '//lib:onos-yang-compiler-api',
    '//lib:onos-yang-runtime',
    '//lib:onos-yang-serializers-json',
    '//lib:onos-yang-serializers-xml',
    '//lib:onos-yang-serializers-utils',
    '//lib:org.apache.servicemix.bundles.dom4j',
]

BUNDLES = [
    ':onos-apps-yang',
    '//lib:onos-yang-model',
    '//lib:onos-yang-compiler-api',
    '//lib:onos-yang-runtime',
    '//lib:onos-yang-serializers-json',
    '//lib:onos-yang-serializers-xml',
    '//lib:onos-yang-serializers-utils',
]

EXCLUDED_BUNDLES = [
    '//lib:org.apache.servicemix.bundles.dom4j',
]

osgi_jar (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'YANG Compiler and Runtime',
    category = 'Utility',
    url = 'http://onosproject.org',
    description = 'Base application to bring in the YANG libraries and assemble them for other apps to use.',
    included_bundles = BUNDLES,
    excluded_bundles = EXCLUDED_BUNDLES,
)